"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { api, formatDate } from "@/lib/api";
import { AttentionBadge } from "@/components/AttentionPanel";

type Pattern={id:string;normalizedLicensePlate:string;displayLicensePlate:string;score:number;confidence:"LOW"|"MEDIUM"|"HIGH";reasons:string[];lastPassageAt:string;timeZone?:string;location:string;camera:{id:string;name:string}|null};
const labels={LOW:"Laag",MEDIUM:"Gemiddeld",HIGH:"Hoog"};
export default function PatternsPage(){
  const[patterns,setPatterns]=useState<Pattern[]>([]);const[form,setForm]=useState({minScore:"",confidence:"",dateFrom:"",dateTo:"",cameraId:"",location:""});const[cameras,setCameras]=useState<any[]>([]);const[error,setError]=useState("");const[busy,setBusy]=useState(false);
  const load=async()=>{setBusy(true);setError("");try{const params=new URLSearchParams();for(const[key,value]of Object.entries(form))if(value)params.set(key==="minScore"?"minScore":key,value);const result=await api<{patterns:Pattern[]}>(`/attention/patterns?${params}`,{cache:"no-store"});setPatterns(result.patterns)}catch(e){setError(e instanceof Error?e.message:"Patronen ophalen mislukt.")}finally{setBusy(false)}};
  useEffect(()=>{api<{cameras:any[]}>('/cameras').then(r=>setCameras(r.cameras)).catch(()=>undefined);void load()},[]);
  return <><div className="page-header"><div><h1>Opvallende patronen</h1><p>Beschikbare aandachtsscores, hoogste score eerst. Dit is geen oordeel over personen.</p></div></div>{error&&<div className="alert error" role="alert">{error}</div>}<form className="card search-form" onSubmit={(event)=>{event.preventDefault();void load()}}><div className="form-grid"><div className="field"><label>Minimumscore</label><input type="number" min="0" max="100" value={form.minScore} onChange={e=>setForm({...form,minScore:e.target.value})} placeholder="Bijv. 70"/></div><div className="field"><label>Betrouwbaarheid</label><select value={form.confidence} onChange={e=>setForm({...form,confidence:e.target.value})}><option value="">Alle</option><option value="HIGH">Hoog</option><option value="MEDIUM">Gemiddeld</option><option value="LOW">Laag</option></select></div><div className="field"><label>Datum vanaf</label><input type="date" value={form.dateFrom} onChange={e=>setForm({...form,dateFrom:e.target.value})}/></div><div className="field"><label>Datum tot</label><input type="date" value={form.dateTo} onChange={e=>setForm({...form,dateTo:e.target.value})}/></div><div className="field"><label>Camera</label><select value={form.cameraId} onChange={e=>setForm({...form,cameraId:e.target.value})}><option value="">Alle camera’s</option>{cameras.map(camera=><option value={camera.id} key={camera.id}>{camera.name}</option>)}</select></div><div className="field"><label>Locatie</label><input value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></div></div><div className="actions"><button className="button" disabled={busy}>{busy?"Laden…":"Filteren"}</button></div></form><section className="card"><div className="card-header"><h2>Resultaten</h2><span>{patterns.length} kentekens</span></div><div className="pattern-list">{patterns.map(pattern=><Link className="pattern-row" href={`/plates/${pattern.normalizedLicensePlate}`} key={pattern.normalizedLicensePlate}><div><strong>{pattern.displayLicensePlate}</strong><span>{pattern.camera?.name??"Onbekende camera"} · {pattern.location}</span><small>Laatste passage: {formatDate(pattern.lastPassageAt,pattern.timeZone)}</small></div><div className="pattern-score"><AttentionBadge attention={pattern}/><small>{labels[pattern.confidence]}</small></div><p>{pattern.reasons[0]??"Geen hoofdreden beschikbaar."}</p></Link>)}{!patterns.length&&<div className="empty">Geen beschikbare patronen voor deze filters.</div>}</div></section></>;
}
