import{beforeEach,describe,expect,it,vi}from"vitest";
import{AttentionAnalysisService}from"./attention-analysis.js";

const current={id:"passage",normalizedLicensePlate:"12ABC3",timestamp:new Date("2026-09-18T05:05:00Z"),timezone:"Europe/Amsterdam",cameraId:"camera-a",location:"Uddel",direction:"OUTGOING",expiresAt:new Date("2026-10-02T05:05:00Z")};
const prisma:any={attentionAnalysisJob:{findFirst:vi.fn(),updateMany:vi.fn(),findUnique:vi.fn(),update:vi.fn(),delete:vi.fn()},passage:{findFirst:vi.fn(),findMany:vi.fn()},attentionSnapshot:{findMany:vi.fn(),upsert:vi.fn(),deleteMany:vi.fn()},$transaction:vi.fn()};
const logger={info:vi.fn(),warn:vi.fn(),error:vi.fn()};
beforeEach(()=>{vi.clearAllMocks();prisma.attentionAnalysisJob.findFirst.mockResolvedValue({id:"job",passageId:"passage",status:"PENDING"});prisma.attentionAnalysisJob.updateMany.mockResolvedValue({count:1});prisma.passage.findFirst.mockResolvedValue(current);prisma.passage.findMany.mockResolvedValue(Array.from({length:6},(_,index)=>({...current,timestamp:new Date(current.timestamp.getTime()-(index+1)*86_400_000)})));prisma.attentionSnapshot.findMany.mockResolvedValue([]);prisma.$transaction.mockImplementation((fn:any)=>fn({attentionSnapshot:prisma.attentionSnapshot,attentionAnalysisJob:prisma.attentionAnalysisJob}))});

describe("duurzame aandachtsscoretaken",()=>{
  it("claimt één taak, leest maximaal 90 dagen begrensd en bewaart een uitlegbaar snapshot",async()=>{const handled=await new AttentionAnalysisService({prisma,logger}).runNext(new Date("2026-09-18T05:06:00Z"));expect(handled).toBe(true);expect(prisma.passage.findMany).toHaveBeenCalledWith(expect.objectContaining({take:5000,where:expect.objectContaining({normalizedLicensePlate:"12ABC3",timestamp:expect.objectContaining({lt:current.timestamp})})}));expect(prisma.attentionSnapshot.upsert).toHaveBeenCalledWith(expect.objectContaining({create:expect.objectContaining({normalizedLicensePlate:"12ABC3",factorsJson:expect.any(Object),reasonsJson:expect.any(Array),expiresAt:current.expiresAt})}));expect(prisma.attentionAnalysisJob.update).toHaveBeenCalledWith({where:{id:"job"},data:{status:"COMPLETED",lockedAt:null,lastError:null}})});
  it("doet niets wanneer geen taak beschikbaar is",async()=>{prisma.attentionAnalysisJob.findFirst.mockResolvedValue(null);expect(await new AttentionAnalysisService({prisma,logger}).runNext()).toBe(false);expect(prisma.passage.findFirst).not.toHaveBeenCalled()});
  it("verwijdert afgeleide snapshots die verlopen of bij verwijderde passages horen",async()=>{await new AttentionAnalysisService({prisma,logger}).cleanup(new Date("2026-09-18T12:00:00Z"));expect(prisma.attentionSnapshot.deleteMany).toHaveBeenCalledWith({where:{OR:[{expiresAt:{lte:new Date("2026-09-18T12:00:00Z")}},{passage:{status:"DELETED"}}]}})});
});
