"use client";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { normalizeCameraHost } from "@anpr/shared";
import { api, formatDate } from "@/lib/api";
import type { VpnLocation } from "@/lib/locations";
import { ItsapiSetup } from "@/components/ItsapiSetup";
import { CameraDiagnostics } from "@/components/CameraDiagnostics";
// getRandomValues also works on HTTP LAN origins, where randomUUID is unavailable.
function draftUuid(){const bytes=crypto.getRandomValues(new Uint8Array(16));bytes[6]=(bytes[6]!&15)|64;bytes[8]=(bytes[8]!&63)|128;const hex=Array.from(bytes,b=>b.toString(16).padStart(2,"0")).join("");return `${hex.slice(0,8)}-${hex.slice(8,12)}-${hex.slice(12,16)}-${hex.slice(16,20)}-${hex.slice(20)}`;}
const initial={name:"",location:"",locationId:"",rtspHost:"",username:"",password:"",connectionMode:"FIELDS",rtspUrl:"",rtspPort:554,rtspPath:"/cam/realmonitor?channel=1&subtype=0",rtspEnabled:true,anprProvider:"DAHUA_ITSAPI",direction:"BOTH",directionMapping:"TOWARD_CAMERA_IS_INCOMING"};
type Video={success:boolean;checkedAt:string;snapshotAt?:string;snapshotObjectId?:string;stale?:boolean;rtspVideo:{status:string;message?:string};snapshot:{status:string;message?:string}};
export default function CameraWizard(){
  const router=useRouter();const[step,setStep]=useState(1);const[form,setForm]=useState(initial);const[network,setNetwork]=useState("LAN");const[locations,setLocations]=useState<VpnLocation[]>([]);const[id,setId]=useState("");const[key,setKey]=useState("");const[busy,setBusy]=useState(false);const[ready,setReady]=useState(false);const[error,setError]=useState("");const[video,setVideo]=useState<Video>();const[active,setActive]=useState(true);const lock=useRef(false);const saved=useRef("");
  const payload=(value= form)=>({...value,locationId:value.locationId||null,username:value.username||undefined,password:value.password||undefined,rtspUrl:value.rtspUrl||undefined});
  useEffect(()=>{void api<{locations:VpnLocation[]}>("/locations").then(r=>setLocations(r.locations)).catch(()=>{});
    const query=new URLSearchParams(window.location.search);const draft=query.get("draft")??sessionStorage.getItem("anpr-camera-draft-id");const draftKey=sessionStorage.getItem("anpr-camera-draft-key")??draftUuid();sessionStorage.setItem("anpr-camera-draft-key",draftKey);setKey(draftKey);
    if(draft)void api<{camera:any}>(`/cameras/${draft}`).then(({camera:c})=>{if(!c.isDraft){sessionStorage.removeItem("anpr-camera-draft-id");const freshKey=draftUuid();sessionStorage.setItem("anpr-camera-draft-key",freshKey);setKey(freshKey);window.history.replaceState(null,"","/cameras/new");return;}const value={...initial,...Object.fromEntries(Object.keys(initial).filter(k=>c[k]!=null).map(k=>[k,c[k]])),username:"",password:"",rtspUrl:"",connectionMode:"FIELDS",locationId:c.locationId??""} as typeof initial;setForm(value);setNetwork(c.locationId?"VPN":"LAN");setId(c.id);setKey(c.draftKey);saved.current=JSON.stringify(payload(value));if(c.videoTestVersion===c.configVersion)setVideo(c.videoTest);}).catch(e=>{sessionStorage.removeItem("anpr-camera-draft-id");const freshKey=draftUuid();sessionStorage.setItem("anpr-camera-draft-key",freshKey);setKey(freshKey);window.history.replaceState(null,"","/cameras/new");setError(e.message)}).finally(()=>setReady(true));else setReady(true);
  },[]);
  const set=(k:keyof typeof initial,v:string|number|boolean)=>{setForm(current=>({...current,[k]:v}));setVideo(undefined)};
  const persist=async()=>{
    if(!form.name.trim()||!form.location.trim())throw new Error("Vul cameranaam en locatie in.");
    if(network==="VPN"&&!form.locationId)throw new Error("Kies een bestaande VPN-locatie.");
    const body=payload();const fingerprint=JSON.stringify(body);
    if(id){if(saved.current!==fingerprint){await api(`/cameras/${id}`,{method:"PATCH",body:JSON.stringify(body)});saved.current=fingerprint;}return id;}
    const r=await api<{camera:{id:string}}>("/camera-drafts",{method:"POST",body:JSON.stringify({...body,draftKey:key})});setId(r.camera.id);sessionStorage.setItem("anpr-camera-draft-id",r.camera.id);saved.current=fingerprint;window.history.replaceState(null,"",`?draft=${r.camera.id}`);return r.camera.id;
  };
  const action=async(work:()=>Promise<void>)=>{if(lock.current)return;lock.current=true;setBusy(true);setError("");try{await work()}catch(e){setError(e instanceof Error?e.message:"Actie mislukt.")}finally{setBusy(false);lock.current=false}};
  const test=()=>action(async()=>{setVideo(undefined);const cameraId=await persist();setVideo(await api(`/cameras/${cameraId}/test-video`,{method:"POST"}));});
  const next=()=>action(async()=>{await persist();setStep(s=>Math.min(4,s+1))});
  const finish=()=>action(async()=>{const cameraId=await persist();await api(`/cameras/${cameraId}/finalize`,{method:"POST",body:JSON.stringify({active})});sessionStorage.removeItem("anpr-camera-draft-id");sessionStorage.removeItem("anpr-camera-draft-key");router.push(`/cameras/${cameraId}/diagnose?saved=1`)});
  if(!ready)return <p>Concept controleren…</p>;
  return <div className="wizard"><div className="page-header"><div><h1>Dahua ANPR-camera toevoegen</h1><p>Beeld en kentekengegevens worden afzonderlijk gecontroleerd.</p></div></div>
    <ol className="steps" aria-label="Wizardstappen">{["Camera","Beeld controleren","Kentekengegevens koppelen","Praktijktest en afronden"].map((label,i)=><li className={`step ${step===i+1?"active":""}`} aria-current={step===i+1?"step":undefined} key={label}><span className="step-number">{i+1}</span><span>{label}</span></li>)}</ol>
    {id&&<p className="alert info">Concept opgeslagen. Je kunt teruggaan of later hervatten. Het concept vervalt na zeven dagen; uploadgegevens en secrets worden dan opgeruimd.</p>}
    <section className="card wizard-card">{error&&<p role="alert" className="alert error">{error}</p>}
    {step===1&&<><h2>Camera</h2><div className="form-grid">
      <div className="field"><label htmlFor="camera-name">Cameranaam</label><input id="camera-name" value={form.name} onChange={e=>set("name",e.target.value)} required/></div>
      <div className="field"><label htmlFor="camera-location">Locatie</label><input id="camera-location" value={form.location} onChange={e=>set("location",e.target.value)} required/></div>
      <div className="field"><label htmlFor="camera-network">Verbinding</label><select id="camera-network" value={network} onChange={e=>{setNetwork(e.target.value);if(e.target.value==="LAN")set("locationId","")}}><option value="LAN">Lokaal netwerk</option><option value="VPN">Via bestaande VPN-locatie</option></select></div>
      {network==="VPN"&&<div className="field"><label htmlFor="camera-vpn">VPN-locatie</label><select id="camera-vpn" value={form.locationId} onChange={e=>set("locationId",e.target.value)}><option value="">Kies een bestaande locatie</option>{locations.map(l=><option value={l.id} key={l.id}>{l.name} ({l.remoteLanCidr})</option>)}</select><small>RTSP gaat naar de camera; ITSAPI komt vanuit de camera. Test beide richtingen. Overlappende lokale en externe subnetten kunnen routering verhinderen; controleer de subnetten zonder ze automatisch te wijzigen.</small><Link href="/locations">VPN-locaties beheren</Link></div>}
      <div className="field"><label htmlFor="direction-mapping">Fysieke richtingsmapping</label><select id="direction-mapping" value={form.directionMapping} onChange={e=>set("directionMapping",e.target.value)}><option value="TOWARD_CAMERA_IS_INCOMING">Naar camera toe = Inkomend</option><option value="AWAY_FROM_CAMERA_IS_INCOMING">Van camera af = Inkomend</option></select><small>Kies welke fysieke beweging voor deze opstelling als inkomend geldt.</small></div><div className="field"><label htmlFor="camera-host">Camera-IP / hostnaam</label><input id="camera-host" value={form.rtspHost} onChange={e=>set("rtspHost",e.target.value)} onBlur={()=>{if(form.rtspHost)try{set("rtspHost",normalizeCameraHost(form.rtspHost));setError("")}catch(e){setError((e as Error).message)}}} placeholder="192.168.178.248"/></div>
      <div className="field"><label htmlFor="camera-user">Camera-gebruikersnaam</label><input id="camera-user" autoComplete="off" value={form.username} onChange={e=>set("username",e.target.value)} placeholder={id?"Leeg: opgeslagen inlog behouden":""}/></div>
      <div className="field"><label htmlFor="camera-password">Camera-wachtwoord</label><input id="camera-password" type="password" autoComplete="new-password" value={form.password} onChange={e=>set("password",e.target.value)} placeholder={id?"Leeg: opgeslagen wachtwoord behouden":""}/></div>
    </div><p>Deze inloggegevens gebruikt het platform om beeld of ondersteunde apparaatgegevens bij de camera op te halen.</p>
    <details><summary>Geavanceerd</summary><div className="form-grid"><div className="field"><label htmlFor="rtsp-mode">Streaminvoer</label><select id="rtsp-mode" value={form.connectionMode} onChange={e=>set("connectionMode",e.target.value)}><option value="FIELDS">Losse gegevens</option><option value="URL">Volledige RTSP-URL</option></select></div>{form.connectionMode==="URL"?<div className="field full"><label htmlFor="rtsp-url">Volledige RTSP-URL</label><input id="rtsp-url" type="password" autoComplete="off" value={form.rtspUrl} onChange={e=>set("rtspUrl",e.target.value)}/></div>:<><div className="field"><label htmlFor="rtsp-port">RTSP-poort</label><input id="rtsp-port" type="number" min="1" max="65535" value={form.rtspPort} onChange={e=>set("rtspPort",Number(e.target.value))}/></div><div className="field full"><label htmlFor="rtsp-path">Streampad</label><input id="rtsp-path" value={form.rtspPath} onChange={e=>set("rtspPath",e.target.value)}/></div></>}<div className="field"><label htmlFor="camera-provider">Bestaand alternatief</label><select id="camera-provider" value={form.anprProvider} onChange={e=>set("anprProvider",e.target.value)}><option value="DAHUA_ITSAPI">Dahua ANPR-camera (ITSAPI-upload)</option><option value="DAHUA_CGI">Dahua CGI-eventstream (geen ITSAPI)</option><option value="NONE">Alleen beeld</option></select></div></div><Link href="/cameras/advanced/new">Bestaande geavanceerde transport- en zone-invoer</Link></details></>}
    {step===2&&<><h2>Beeld controleren</h2><p>De backend opent een nieuwe RTSP-sessie en decodeert een nieuw frame. Een open netwerkpoort is onvoldoende.</p><button type="button" className="button" disabled={busy} onClick={test}>{busy?"Nieuw beeld ophalen…":"Beeld testen"}</button><div aria-live="polite"><p>Stream: {video?.stale?"Resultaat verouderd":video?video.success?"Geslaagd – videoframe gedecodeerd":"Mislukt":"Niet getest"}</p><p>{video?.rtspVideo.message}</p><p>Snapshot: {video?.snapshot.status==="AVAILABLE"?"Beschikbaar":video?"Niet beschikbaar":"Niet getest"}</p><p>{video?.snapshot.message}</p></div>{video?.snapshotObjectId&&!video.stale&&<figure className="wizard-preview"><img src={`/api/cameras/test-snapshot/${video.snapshotObjectId.split("/").pop()}`} alt="Nieuw opgehaald camerabeeld"/><figcaption>Nieuw beeld: {formatDate(video.snapshotAt)}</figcaption></figure>}{!video?.success&&<p className="alert info">Kentekengegevens kunnen afzonderlijk worden getest. Livebeeld werkt nog niet.</p>}</>}
    {step===3&&<><h2>Kentekengegevens koppelen</h2>{form.anprProvider==="DAHUA_ITSAPI"?<ItsapiSetup cameraId={id} onChanged={()=>setVideo(undefined)}/>:<p>Je gebruikt het bestaande alternatief {form.anprProvider}. Dit is geen ITSAPI-upload. Controleer de aparte diagnose na opslaan.</p>}</>}
    {step===4&&<><h2>Praktijktest en afronden</h2><ol><li>Controleer eerst dat de camera zelf een voertuigpassage herkent.</li><li>Controleer geauthenticeerde ontvangst, Device ID en een geldige heartbeat.</li><li>Laat één voertuig passeren en controleer welke velden en beelden zijn ontvangen.</li><li>Na afronden: controleer Live passages en Zoeken. Alleen een eigen watchlistmatch maakt een hit.</li><li>Optioneel: test push en bevestig ontvangst op het bedoelde toestel.</li></ol><p>Conceptuploads veroorzaken geen productiepush. Softwaretests bewijzen geen cameraverbinding. Je kunt opslaan met openstaande controles.</p><label className="checkbox"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/>Camera na afronden inschakelen</label><CameraDiagnostics cameraId={id}/></>}
    <div className="actions wizard-navigation">{step>1&&<button type="button" className="button secondary" disabled={busy} onClick={()=>{setError("");setStep(s=>s-1)}}>Vorige</button>}{step<4?<button type="button" className="button" disabled={busy} onClick={next}>Volgende</button>:<button type="button" className="button" disabled={busy} onClick={finish}>Opslaan met bovenstaande teststatus</button>}</div></section>
  </div>;
}
