"use client";
import { PointerEvent, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { api, ApiError } from "@/lib/api";

type Point={x:number;y:number};
const initial={name:"",location:"",description:"",direction:"INCOMING",latitude:"",longitude:"",connectionMode:"FIELDS",rtspUrl:"",rtspHost:"",rtspPort:"554",rtspPath:"/",username:"",password:"",active:true};
export default function CameraWizard(){const router=useRouter();const[step,setStep]=useState(1);const[form,setForm]=useState(initial);const[error,setError]=useState("");const[busy,setBusy]=useState(false);const[test,setTest]=useState<any>();const[zone,setZone]=useState<Point[]>([]);const[start,setStart]=useState<Point>();const area=useRef<HTMLDivElement>(null);
  const set=(key:string,value:any)=>setForm(f=>({...f,[key]:value}));
  const connection=useMemo(()=>({connectionMode:form.connectionMode,rtspUrl:form.rtspUrl||undefined,rtspHost:form.rtspHost||undefined,rtspPort:Number(form.rtspPort),rtspPath:form.rtspPath||undefined,username:form.username||undefined,password:form.password||undefined}),[form]);
  const validate=()=>{if(step===1&&(!form.name.trim()||!form.location.trim()))return"Vul minimaal cameranaam en locatie in.";if(step===2&&!test?.success)return"Test eerst de RTSP-verbinding succesvol.";return""};
  const next=()=>{const issue=validate();if(issue){setError(issue);return}setError("");setStep(s=>Math.min(5,s+1));};
  const testConnection=async()=>{setBusy(true);setError("");setTest(undefined);try{const result=await api<any>("/cameras/test-connection",{method:"POST",body:JSON.stringify(connection)});setTest(result);if(!result.success)setError(result.message);}catch(e){setError(e instanceof ApiError?e.message:"Verbindingstest mislukt.");}finally{setBusy(false)}};
  const point=(e:PointerEvent)=>{const rect=area.current!.getBoundingClientRect();return{x:Math.max(0,Math.min(1,(e.clientX-rect.left)/rect.width)),y:Math.max(0,Math.min(1,(e.clientY-rect.top)/rect.height))}};
  const down=(e:PointerEvent)=>{e.currentTarget.setPointerCapture(e.pointerId);const p=point(e);setStart(p);setZone([p,p]);};const move=(e:PointerEvent)=>{if(!start)return;setZone([start,point(e)]);};const up=()=>setStart(undefined);
  const box=zone.length===2?{left:`${Math.min(zone[0]!.x,zone[1]!.x)*100}%`,top:`${Math.min(zone[0]!.y,zone[1]!.y)*100}%`,width:`${Math.abs(zone[1]!.x-zone[0]!.x)*100}%`,height:`${Math.abs(zone[1]!.y-zone[0]!.y)*100}%`}:undefined;
  const save=async()=>{setBusy(true);setError("");try{const points=zone.length===2?[zone[0],{x:zone[1]!.x,y:zone[0]!.y},zone[1],{x:zone[0]!.x,y:zone[1]!.y}]:undefined;const body={...connection,name:form.name,location:form.location,description:form.description||undefined,direction:form.direction,latitude:form.latitude?Number(form.latitude):null,longitude:form.longitude?Number(form.longitude):null,active:form.active,zone:points?{type:"RECTANGLE",points}:undefined};const created=await api<any>("/cameras",{method:"POST",body:JSON.stringify(body)});if(test?.success)await api(`/cameras/${created.camera.id}/test`,{method:"POST"});router.push("/cameras");}catch(e){setError(e instanceof ApiError?e.message:"Camera opslaan mislukt.");}finally{setBusy(false)}};
  const labels=["Algemeen","Verbinding","Herkenningsgebied","Test ANPR","Afronden"];
  return <div className="wizard"><div className="page-header"><div><h1>Camera toevoegen</h1><p>Doorloop vijf overzichtelijke stappen.</p></div></div><div className="steps">{labels.map((l,i)=><div className={`step ${step===i+1?"active":step>i+1?"done":""}`} key={l}><div className="step-number">{step>i+1?"✓":i+1}</div><span className="step-label">{l}</span></div>)}</div><section className="card wizard-card">{error&&<div className="alert error">{error}</div>}
  {step===1&&<><h2>Algemene informatie</h2><p className="subtitle">Geef de camera een herkenbare naam en locatie.</p><div className="form-grid"><div className="field"><label>Cameranaam *</label><input value={form.name} onChange={e=>set("name",e.target.value)} placeholder="Bijvoorbeeld Uddel Noord"/></div><div className="field"><label>Locatie *</label><input value={form.location} onChange={e=>set("location",e.target.value)} placeholder="Straat of gebied"/></div><div className="field full"><label>Omschrijving</label><textarea value={form.description} onChange={e=>set("description",e.target.value)} placeholder="Aanvullende informatie"/></div><div className="field"><label>Rijrichting</label><select value={form.direction} onChange={e=>set("direction",e.target.value)}><option value="INCOMING">Inkomend</option><option value="OUTGOING">Uitgaand</option><option value="BOTH">Beide richtingen</option></select></div><div/><div className="field"><label>Latitude</label><input type="number" step="any" value={form.latitude} onChange={e=>set("latitude",e.target.value)} placeholder="52.25"/><small>Kaartselectie is TODO voor een latere interfacefase; coördinaten werken nu al.</small></div><div className="field"><label>Longitude</label><input type="number" step="any" value={form.longitude} onChange={e=>set("longitude",e.target.value)} placeholder="5.78"/></div></div></>}
  {step===2&&<><h2>RTSP-verbinding</h2><p className="subtitle">Credentials worden server-side versleuteld en nooit teruggestuurd.</p><div className="mode-select"><button className={form.connectionMode==="FIELDS"?"active":""} onClick={()=>set("connectionMode","FIELDS")}><strong>Losse gegevens</strong><span>Host, poort, pad en inloggegevens</span></button><button className={form.connectionMode==="URL"?"active":""} onClick={()=>set("connectionMode","URL")}><strong>Volledige RTSP URL</strong><span>De API ontleedt en beveiligt credentials</span></button></div>{form.connectionMode==="URL"?<div className="field"><label>RTSP URL *</label><input type="password" autoComplete="off" value={form.rtspUrl} onChange={e=>set("rtspUrl",e.target.value)} placeholder="rtsp://gebruiker:wachtwoord@camera:554/stream"/><small>De waarde wordt verborgen tijdens invoer en nooit door de API teruggegeven.</small></div>:<div className="form-grid"><div className="field"><label>IP-adres of hostnaam *</label><input value={form.rtspHost} onChange={e=>set("rtspHost",e.target.value)} placeholder="192.168.1.50"/></div><div className="field"><label>RTSP-poort</label><input type="number" value={form.rtspPort} onChange={e=>set("rtspPort",e.target.value)}/></div><div className="field full"><label>Stream/path</label><input value={form.rtspPath} onChange={e=>set("rtspPath",e.target.value)} placeholder="/cam/realmonitor?channel=1&subtype=0"/></div><div className="field"><label>Gebruikersnaam</label><input autoComplete="off" value={form.username} onChange={e=>set("username",e.target.value)}/></div><div className="field"><label>Wachtwoord</label><input type="password" autoComplete="new-password" value={form.password} onChange={e=>set("password",e.target.value)}/></div></div>}<div className="actions" style={{justifyContent:"flex-start"}}><button className="button" disabled={busy} onClick={testConnection}>{busy?"FFmpeg test verbinding…":"Verbinding testen"}</button></div>{test?.success&&<div className="alert success">Verbinding geslaagd in {test.responseTimeMs} ms.{test.snapshotObjectId&&" Snapshot ontvangen."}</div>}{test?.snapshotObjectId&&<div className="wizard-preview"><img src={`/api/cameras/test-snapshot/${test.snapshotObjectId.split("/").pop()}`} alt="RTSP testsnapshot"/></div>}</>}
  {step===3&&<><h2>Herkenningsgebied</h2><p className="subtitle">Sleep over de snapshot om een rechthoek te tekenen. De coördinaten worden genormaliseerd opgeslagen.</p><div ref={area} className="snapshot-zone" onPointerDown={down} onPointerMove={move} onPointerUp={up}>{test?.snapshotObjectId?<img draggable={false} src={`/api/cameras/test-snapshot/${test.snapshotObjectId.split("/").pop()}`} alt="Camera snapshot"/>:<span>Geen snapshot ontvangen; zone kan alsnog op het vlak worden ingesteld.</span>}{box&&<div className="zone-box" style={box}/>}</div><div className="actions" style={{justifyContent:"flex-start"}}><button className="button secondary" onClick={()=>setZone([])}>Zone wissen</button></div></>}
  {step===4&&<><h2>Test ANPR</h2><p className="subtitle">ANPR-herkenning wordt bewust nog niet gesimuleerd als echte detectie.</p><div className="todo"><strong>TODO — Fase 2</strong>Echte kenteken- en voertuigclassificatie wordt in Fase 2 via een verwisselbare ANPR-provider toegevoegd. De demosimulator staat los van deze camera.</div></>}
  {step===5&&<><h2>Camera afronden</h2><p className="subtitle">Controleer de gegevens en kies of de camera direct actief wordt.</p><div className="summary"><div><span>Naam</span><strong>{form.name}</strong></div><div><span>Locatie</span><strong>{form.location}</strong></div><div><span>Rijrichting</span><strong>{form.direction}</strong></div><div><span>Verbinding</span><strong>{test?.success?"Succesvol getest":"Niet getest"}</strong></div><div><span>Herkenningszone</span><strong>{zone.length?"Ingesteld":"Niet ingesteld"}</strong></div><div><span>ANPR</span><strong>TODO Fase 2</strong></div></div><label className="checkbox" style={{marginTop:20}}><input type="checkbox" checked={form.active} onChange={e=>set("active",e.target.checked)}/>Camera na opslaan activeren</label></>}
  <div className="actions wizard-navigation">{step>1&&<button className="button secondary" onClick={()=>{setError("");setStep(s=>s-1)}}>Vorige</button>}{step<5?<button className="button" onClick={next}>Volgende</button>:<button className="button" disabled={busy} onClick={save}>{busy?"Camera opslaan…":"Camera activeren en opslaan"}</button>}</div></section></div>}
