CREATE TYPE "CameraDirectionMapping" AS ENUM ('TOWARD_CAMERA_IS_INCOMING', 'AWAY_FROM_CAMERA_IS_INCOMING');

ALTER TABLE "Camera"
ADD COLUMN "directionMapping" "CameraDirectionMapping" NOT NULL DEFAULT 'TOWARD_CAMERA_IS_INCOMING';
