"use client";
import {directionLabel} from "@anpr/shared";
import Link from "next/link";
import { useEffect, useState } from "react";
import { api, formatDate } from "@/lib/api";

type Data = { counters:{cameraTotal:number;cameraOnline:number;passagesToday:number;hitsToday:number;watchedPlates:number;demoPassagesToday:number;demoHitsToday:number}; recentPassages:Array<any>;recentHits:Array<any>;cameraProblems:Array<any> };
export default function Dashboard() {
  const [data,setData]=useState<Data>(); const [error,setError]=useState("");
  useEffect(()=>{
    let mounted=true, loading=false;
    const load=async()=>{if(loading)return;loading=true;try{const result=await api<Data>("/dashboard",{cache:"no-store"});if(mounted){setData(result);setError("")}}catch(e){if(mounted)setError(e instanceof Error?e.message:"Dashboard ophalen mislukt.")}finally{loading=false}};
    void load();const timer=window.setInterval(()=>void load(),3000);
    return()=>{mounted=false;window.clearInterval(timer)};
  },[]);
  if(!data&&error)return <div className="alert error">{error}</div>; if(!data)return <div className="loading"><span className="spinner"/>Dashboard laden…</div>;
  const metrics=[["Camera’s online",`${data.counters.cameraOnline} / ${data.counters.cameraTotal}`],["Passages vandaag",data.counters.passagesToday],["Hits vandaag",data.counters.hitsToday],["Signaleringslijst",data.counters.watchedPlates],["Storingen",data.cameraProblems.length]];
  return <><div className="page-header"><div><h1>Dashboard</h1><p>Actueel overzicht van het ANPR-platform.</p></div><span className="badge green"><span className="dot"/>Elke 3 seconden bijgewerkt</span></div>{error&&<div className="alert error" role="status">Verversen mislukt: {error}. Het laatst opgehaalde overzicht blijft zichtbaar.</div>}<div className="demo-banner">Tellingen bevatten echte en DEMO-data. Vandaag: {data.counters.demoPassagesToday} demopassages en {data.counters.demoHitsToday} demo-hits. Daggrens: Europe/Amsterdam.</div><div className="cards">{metrics.map(([label,value])=><div className="metric" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><div className="grid-2"><section className="card"><div className="card-header"><h2>Recente passages</h2><Link href="/passages" className="text-link">Alles bekijken</Link></div>{data.recentPassages.length?<div className="table-wrap"><table className="mobile-stack-table"><thead><tr><th>Kenteken</th><th>Camera</th><th>Tijd</th><th>Bron</th></tr></thead><tbody>{data.recentPassages.map(p=><tr key={p.id}><td data-label="Kenteken"><Link className="text-link" href={`/passages/${p.id}`}><strong>{p.displayLicensePlate}</strong></Link></td><td data-label="Camera">{p.camera.name}</td><td data-label="Tijd">{formatDate(p.timestamp,p.timeZone)}<small className="block-muted">{directionLabel(p.direction,true)}</small></td><td data-label="Bron"><span className={`badge ${p.source==="DEMO"?"amber":"gray"}`}>{p.source}</span></td></tr>)}</tbody></table></div>:<div className="empty">Nog geen passages.</div>}</section><section className="card"><div className="card-header"><h2>Laatste hits</h2><small>Vandaag · nieuwste vijf</small><Link href="/hits" className="text-link">Alles bekijken</Link></div>{data.recentHits.length?data.recentHits.map(h=><Link href={`/hits/${h.id}`} className="alert error hit-link" key={h.id}><strong>{h.passage?.displayLicensePlate??h.normalizedLicensePlate}</strong>{h.passage?.source==="DEMO"&&<span className="badge amber">DEMO</span>}<small>{h.camera.name} · {formatDate(h.timestamp,h.timeZone)} · {directionLabel(h.passage?.direction,true)}</small><div className="dashboard-hit-groups">{h.groups.slice(0,2).map((group:any)=><div key={group.id}><strong>{group.name}</strong><span>{group.reason||"Geen reden vastgelegd"}</span></div>)}{h.groups.length>2&&<span>+{h.groups.length-2} groepen · bekijk hitdetails</span>}</div></Link>):<div className="empty">Vandaag nog geen hits.</div>}<div className="card-header" style={{marginTop:20}}><h2>Camerastoringen</h2></div>{data.cameraProblems.length?data.cameraProblems.map(c=><div className="alert error" key={c.id}>{c.name}: {c.lastConnectionError??c.status}</div>):<div className="alert success">Geen actieve camerastoringen.</div>}</section></div></>;
}
