"use client";
import { useEffect, useState } from "react";
import { api, formatDate } from "@/lib/api";

type Data = { counters:{cameraTotal:number;cameraOnline:number;passagesToday:number;hitsToday:number;watchedPlates:number}; recentPassages:Array<any>;recentHits:Array<any>;cameraProblems:Array<any> };
export default function Dashboard() {
  const [data,setData]=useState<Data>(); const [error,setError]=useState("");
  useEffect(()=>{api<Data>("/dashboard").then(setData).catch((e)=>setError(e.message));},[]);
  if(error)return <div className="alert error">{error}</div>; if(!data)return <div className="loading"><span className="spinner"/>Dashboard laden…</div>;
  const metrics=[["Camera’s online",`${data.counters.cameraOnline} / ${data.counters.cameraTotal}`],["Passages vandaag",data.counters.passagesToday],["Hits vandaag",data.counters.hitsToday],["Signaleringslijst",data.counters.watchedPlates],["Storingen",data.cameraProblems.length]];
  return <><div className="page-header"><div><h1>Dashboard</h1><p>Actueel overzicht van het ANPR-platform.</p></div><span className="badge green"><span className="dot"/>Systeem actief</span></div><div className="demo-banner">DEMO-data is herkenbaar gemarkeerd en is geen echte ANPR-detectie.</div><div className="cards">{metrics.map(([label,value])=><div className="metric" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><div className="grid-2"><section className="card"><div className="card-header"><h2>Recente passages</h2><span className="badge gray">Live verversing: Fase 2</span></div>{data.recentPassages.length?<div className="table-wrap"><table><thead><tr><th>Kenteken</th><th>Camera</th><th>Tijd</th><th>Bron</th></tr></thead><tbody>{data.recentPassages.map(p=><tr key={p.id}><td><strong>{p.displayLicensePlate}</strong></td><td>{p.camera.name}</td><td>{formatDate(p.timestamp)}</td><td><span className={`badge ${p.source==="DEMO"?"amber":"gray"}`}>{p.source}</span></td></tr>)}</tbody></table></div>:<div className="empty">Nog geen passages.</div>}</section><section className="card"><div className="card-header"><h2>Laatste hits</h2></div>{data.recentHits.length?data.recentHits.map(h=><div className="alert error" key={h.id}><strong>{h.normalizedLicensePlate}</strong><br/><small>{h.camera.name} · {formatDate(h.timestamp)} · {h.group.name}</small></div>):<div className="empty">Geen recente hits.</div>}<div className="card-header" style={{marginTop:20}}><h2>Camerastoringen</h2></div>{data.cameraProblems.length?data.cameraProblems.map(c=><div className="alert error" key={c.id}>{c.name}: {c.lastConnectionError??c.status}</div>):<div className="alert success">Geen actieve camerastoringen.</div>}</section></div></>;
}
