"use client";
import {useEffect,useState} from "react";
import {api} from "@/lib/api";
import {ObservationCollection} from "@/components/ObservationCollection";
import {ViewPreference,useViewPreference} from "@/components/ViewPreference";
export default function HitsPage(){
 const[data,setData]=useState<any>();const[page,setPage]=useState(1);const[error,setError]=useState("");const[mode,setMode]=useViewPreference("hits");
 useEffect(()=>{let mounted=true,busy=false;const load=async()=>{if(busy)return;busy=true;try{const result=await api(`/hits?page=${page}&limit=25`,{cache:"no-store"});if(mounted){setData(result);setError("")}}catch(e){if(mounted)setError(e instanceof Error?e.message:"Hits ophalen mislukt.")}finally{busy=false}};void load();const timer=setInterval(()=>void load(),3000);return()=>{mounted=false;clearInterval(timer)}},[page]);
 return <><div className="page-header"><div><h1>Hits</h1><p>Groepsmatches met reden en rijrichting · automatisch bijgewerkt.</p></div><ViewPreference mode={mode} onChange={setMode}/></div>{error&&<div className="alert error" role="status">{error}</div>}{!data?<div className="loading">Hits laden…</div>:<><ObservationCollection mode={mode} kind="hits" items={data.hits.map((h:any)=>({id:h.id,passageId:h.passage.id,plate:h.passage.displayLicensePlate,camera:h.camera.name,location:h.location,timestamp:h.timestamp,timeZone:h.timeZone,direction:h.passage.direction,source:h.passage.source,hit:true,groups:h.groups,status:h.notificationStatus,imageKind:h.passage.vehicleImage1ObjectId?"overview":h.passage.plateImageObjectId?"plate":undefined}))}/>{!data.hits.length&&<div className="card empty">Nog geen hits.</div>}<div className="pagination"><button className="button secondary" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Vorige</button><span>Pagina {page} van {Math.max(1,Math.ceil(data.total/data.limit))}</span><button className="button secondary" disabled={page*data.limit>=data.total} onClick={()=>setPage(p=>p+1)}>Volgende</button></div></>}</>;
}
