"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { api, formatDate } from "@/lib/api";

export default function HitsPage(){
  const[data,setData]=useState<any>();const[page,setPage]=useState(1);const[error,setError]=useState("");
  useEffect(()=>{api(`/hits?page=${page}&limit=25`,{cache:"no-store"}).then(setData).catch(e=>setError(e.message))},[page]);
  return <><div className="page-header"><div><h1>Hits</h1><p>Passages die overeenkomen met actieve signaleringsgroepen.</p></div><span className="badge red">Directe detectie</span></div>{error&&<div className="alert error">{error}</div>}{!data?<div className="loading"><span className="spinner"/>Hits laden…</div>:<><div className="hit-grid">{data.hits.map((hit:any)=><Link href={`/hits/${hit.id}`} className="card hit-card" key={hit.id}><div className="passage-image">{hit.passage.vehicleImage1ObjectId?<img src={`/api/passages/${hit.passage.id}/image/overview`} alt="Voertuig bij hit"/>:hit.passage.plateImageObjectId?<img src={`/api/passages/${hit.passage.id}/image/plate`} alt="Kenteken bij hit"/>:<span>Geen foto beschikbaar</span>}<span className="badge red passage-source">HIT</span></div><div className="passage-body"><div className="passage-title"><strong>{hit.passage.displayLicensePlate}</strong>{hit.passage.source==="DEMO"&&<span className="badge amber">DEMO</span>}</div><p>{hit.camera.name} · {hit.location}</p><div className="tag-list">{hit.groups.map((group:any)=><span className="badge" key={group.id} style={{borderColor:group.color}}>{group.name}</span>)}</div><p className="hit-reason">{hit.groups.map((group:any)=>group.reason).filter(Boolean).join(" · ")||"Geen reden opgegeven"}</p><small>{formatDate(hit.timestamp)} · {hit.passage.source}</small></div></Link>)}</div>{!data.hits.length&&<div className="card empty">Nog geen hits.</div>}<div className="pagination"><button className="button secondary" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Vorige</button><span>Pagina {page} van {Math.max(1,Math.ceil(data.total/data.limit))}</span><button className="button secondary" disabled={page*data.limit>=data.total} onClick={()=>setPage(p=>p+1)}>Volgende</button></div></>}</>;
}
