"use client";
import { FormEvent,useEffect,useState } from "react";
import { useParams,useRouter } from "next/navigation";
import { api,ApiError } from "@/lib/api";
import type { VpnLocation } from "@/lib/locations";

type Camera={id:string;name:string;location:string;locationId?:string|null;recorderId?:string|null;description?:string;direction:string;active:boolean;rtspHost?:string;rtspPort:number;rtspPath?:string;latitude?:string;longitude?:string;offlineTimeoutSeconds:number;hasUsername:boolean;hasPassword:boolean;anprProvider:"NONE"|"DAHUA_CGI";anprHttpProtocol:"http"|"https";anprHttpPort:number;anprChannel:number};
export default function EditCamera(){const{id}=useParams<{id:string}>();const router=useRouter();const[form,setForm]=useState<any>();const[locations,setLocations]=useState<VpnLocation[]>([]);const[error,setError]=useState("");const[nameError,setNameError]=useState("");const[success,setSuccess]=useState("");const[busy,setBusy]=useState(false);
  useEffect(()=>{Promise.all([api<{camera:Camera}>(`/cameras/${id}`),api<{locations:VpnLocation[]}>("/locations")]).then(([cameraData,locationData])=>{setForm({...cameraData.camera,username:"",password:""});setLocations(locationData.locations)}).catch(e=>setError(e.message))},[id]);
  const set=(key:string,value:any)=>{setForm((current:any)=>({...current,[key]:value}));if(key==="name")setNameError("")};
  const selectLocation=(locationId:string)=>{const selected=locations.find(item=>item.id===locationId);setForm((current:any)=>({...current,locationId:locationId||null,recorderId:null,location:selected?.name??current.location}))};
  const submit=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setError("");setNameError("");setSuccess("");try{const body={name:form.name,location:form.location,locationId:form.locationId??null,recorderId:form.recorderId??null,description:form.description,direction:form.direction,active:form.active,latitude:form.latitude===""?null:Number(form.latitude),longitude:form.longitude===""?null:Number(form.longitude),offlineTimeoutSeconds:Number(form.offlineTimeoutSeconds),connectionMode:"FIELDS",rtspHost:form.rtspHost,rtspPort:Number(form.rtspPort),rtspPath:form.rtspPath,username:form.username||undefined,password:form.password||undefined,anprProvider:form.anprProvider,anprHttpProtocol:form.anprHttpProtocol,anprHttpPort:Number(form.anprHttpPort),anprChannel:Number(form.anprChannel)};await api(`/cameras/${id}`,{method:"PATCH",body:JSON.stringify(body)});setSuccess("Camera-instellingen zijn opgeslagen. Workers nemen wijzigingen automatisch over.");set("password","")}catch(e){if(e instanceof ApiError&&e.code==="CAMERA_NAME_ALREADY_EXISTS")setNameError(e.fields?.name?.[0]??e.message);setError(e instanceof ApiError?e.message:"Opslaan mislukt.")}finally{setBusy(false)}};
  if(!form&&!error)return <div className="loading"><span className="spinner"/>Camera laden…</div>;
  const selected=locations.find(item=>item.id===form?.locationId);
  return <><div className="page-header"><div><h1>Camera bewerken</h1><p>Wijzig algemene, locatie- en verbindingsinstellingen.</p></div><button className="button secondary" onClick={()=>router.push("/cameras")}>Terug</button></div>{error?<div className="alert error" role="alert">{error}</div>:null}{success?<div className="alert success" role="status">{success}</div>:null}{form?<form className="card" onSubmit={submit}><div className="form-grid">
    <div className="field"><label htmlFor="camera-name">Cameranaam</label><input id="camera-name" required value={form.name} onChange={e=>set("name",e.target.value)} aria-invalid={Boolean(nameError)}/>{nameError?<small className="field-error">{nameError}</small>:null}</div>
    <div className="field"><label>VPN-locatie</label><select value={form.locationId??""} onChange={e=>selectLocation(e.target.value)}><option value="">Standalone camera</option>{locations.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></div>
    <div className="field"><label>Locatietekst</label><input required value={form.location} onChange={e=>set("location",e.target.value)}/></div><div className="field"><label>Recorder</label><select value={form.recorderId??""} disabled={!selected} onChange={e=>set("recorderId",e.target.value||null)}><option value="">Geen recorder</option>{selected?.recorders.map(recorder=><option key={recorder.id} value={recorder.id}>{recorder.name}</option>)}</select></div>
    <div className="field full"><label>Omschrijving</label><textarea value={form.description??""} onChange={e=>set("description",e.target.value)}/></div><div className="field"><label>Rijrichting</label><select value={form.direction} onChange={e=>set("direction",e.target.value)}><option value="INCOMING">Inkomend</option><option value="OUTGOING">Uitgaand</option><option value="BOTH">Beide</option></select></div><div className="field"><label>Offline-timeout (seconden)</label><input type="number" min="30" max="86400" value={form.offlineTimeoutSeconds} onChange={e=>set("offlineTimeoutSeconds",e.target.value)}/></div>
    <div className="field"><label>Latitude</label><input type="number" step="any" value={form.latitude??""} onChange={e=>set("latitude",e.target.value)}/></div><div className="field"><label>Longitude</label><input type="number" step="any" value={form.longitude??""} onChange={e=>set("longitude",e.target.value)}/></div><div className="field"><label>RTSP-host</label><input required value={form.rtspHost??""} onChange={e=>set("rtspHost",e.target.value)}/></div><div className="field"><label>RTSP-poort</label><input type="number" min="1" max="65535" value={form.rtspPort} onChange={e=>set("rtspPort",e.target.value)}/></div>
    <div className="field full"><label>Stream/path</label><input value={form.rtspPath??""} onChange={e=>set("rtspPath",e.target.value)}/></div><div className="field"><label>Nieuwe gebruikersnaam</label><input autoComplete="off" value={form.username} onChange={e=>set("username",e.target.value)} placeholder={form.hasUsername?"Bestaande waarde blijft behouden":"Optioneel"}/></div><div className="field"><label>Nieuw wachtwoord</label><input type="password" autoComplete="new-password" value={form.password} onChange={e=>set("password",e.target.value)} placeholder={form.hasPassword?"Bestaande waarde blijft behouden":"Optioneel"}/></div>
    <div className="field full"><h2>ANPR-events uit de camera</h2></div><div className="field"><label>ANPR-provider</label><select value={form.anprProvider} onChange={e=>set("anprProvider",e.target.value)}><option value="NONE">Uitgeschakeld</option><option value="DAHUA_CGI">Dahua CGI TrafficJunction</option></select></div><div className="field"><label>HTTP-protocol</label><select value={form.anprHttpProtocol} onChange={e=>set("anprHttpProtocol",e.target.value)}><option value="http">HTTP</option><option value="https">HTTPS</option></select></div><div className="field"><label>HTTP-poort</label><input type="number" min="1" max="65535" value={form.anprHttpPort} onChange={e=>set("anprHttpPort",e.target.value)}/></div><div className="field"><label>Recorderkanaal</label><input type="number" min="1" max="64" value={form.anprChannel} onChange={e=>set("anprChannel",e.target.value)}/></div>
    <label className="checkbox full"><input type="checkbox" checked={form.active} onChange={e=>set("active",e.target.checked)}/>Camera actief</label></div><div className="alert info">Opgeslagen credentials worden nooit geladen. Laat de geheime velden leeg om ze te behouden.</div><div className="actions"><button className="button" disabled={busy}>{busy?"Opslaan…":"Wijzigingen opslaan"}</button></div></form>:null}</>}
