"use client";
import Link from "next/link";
import { NativeAnprTest } from "@/components/NativeAnprTest";
import { FormEvent,useEffect,useState } from "react";
import { useParams,useRouter } from "next/navigation";
import { api,ApiError } from "@/lib/api";
import { DahuaTestStatus,type DahuaTestResult } from "@/components/DahuaTestStatus";
import type { VpnLocation } from "@/lib/locations";

type DeviceConnection={id:string;host:string;port:number;requestedCategory:string;hasUsername:boolean;hasPassword:boolean};
type Camera={id:string;name:string;location:string;locationId?:string|null;recorderId?:string|null;description?:string;direction:string;active:boolean;rtspEnabled:boolean;rtspHost?:string;rtspPort:number;rtspPath?:string;latitude?:string;longitude?:string;offlineTimeoutSeconds:number;hasUsername:boolean;hasPassword:boolean;deviceConnections?:DeviceConnection[];anprProvider:"NONE"|"DAHUA_CGI"|"DAHUA_ITSAPI";anprHttpProtocol:"http"|"https";anprHttpPort:number;anprChannel:number};
export default function EditCamera(){const{id}=useParams<{id:string}>();const router=useRouter();const[form,setForm]=useState<any>();const[locations,setLocations]=useState<VpnLocation[]>([]);const[error,setError]=useState("");const[nameError,setNameError]=useState("");const[success,setSuccess]=useState("");const[busy,setBusy]=useState(false);const[tcpResult,setTcpResult]=useState<DahuaTestResult>();
  useEffect(()=>{Promise.all([api<{camera:Camera}>(`/cameras/${id}`),api<{locations:VpnLocation[]}>("/locations")]).then(([cameraData,locationData])=>{const dahua=cameraData.camera.deviceConnections?.[0];setForm({...cameraData.camera,rtspEnabled:cameraData.camera.rtspEnabled,username:"",password:"",dahuaEnabled:Boolean(dahua),dahuaHost:dahua?.host??"",dahuaPort:String(dahua?.port??37777),deviceCategory:dahua?.requestedCategory??"AUTO",dahuaUsername:"",dahuaPassword:"",hasDahuaUsername:dahua?.hasUsername??false,hasDahuaPassword:dahua?.hasPassword??false});setLocations(locationData.locations)}).catch(e=>setError(e.message))},[id]);
  const set=(key:string,value:any)=>{setForm((current:any)=>({...current,[key]:value}));if(key==="name")setNameError("")};
  const selectLocation=(locationId:string)=>{const selected=locations.find(item=>item.id===locationId);setForm((current:any)=>({...current,locationId:locationId||null,recorderId:null,location:selected?.name??current.location}))};
  const testTcp=async()=>{setBusy(true);setError("");setTcpResult(undefined);try{const result=await api<DahuaTestResult>("/device-connections/dahua/test",{method:"POST",body:JSON.stringify({host:form.dahuaHost,port:Number(form.dahuaPort),category:form.deviceCategory,username:form.dahuaUsername||undefined,password:form.dahuaPassword||undefined})});setTcpResult(result);if(!result.tcpPortOpen||result.authentication==="FAILED"||result.deviceApi==="NOT_SUPPORTED")setError(result.message)}catch(e){setError(e instanceof ApiError?e.message:"TCP-test mislukt.")}finally{setBusy(false)}};
  const submit=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setError("");setNameError("");setSuccess("");try{const body={name:form.name,location:form.location,locationId:form.locationId??null,recorderId:form.recorderId??null,description:form.description,direction:form.direction,active:form.active,latitude:form.latitude===""?null:Number(form.latitude),longitude:form.longitude===""?null:Number(form.longitude),offlineTimeoutSeconds:Number(form.offlineTimeoutSeconds),rtspEnabled:form.rtspEnabled,connectionMode:"FIELDS",rtspHost:form.rtspHost,rtspPort:Number(form.rtspPort),rtspPath:form.rtspPath,username:form.username||undefined,password:form.password||undefined,dahuaTcp:form.dahuaEnabled?{host:form.dahuaHost,port:Number(form.dahuaPort),category:form.deviceCategory,username:form.dahuaUsername||undefined,password:form.dahuaPassword||undefined}:null,anprProvider:form.anprProvider,anprHttpProtocol:form.anprHttpProtocol,anprHttpPort:Number(form.anprHttpPort),anprChannel:Number(form.anprChannel)};await api(`/cameras/${id}`,{method:"PATCH",body:JSON.stringify(body)});setSuccess("Camera-instellingen zijn opgeslagen. Workers nemen wijzigingen automatisch over.");set("password","");set("dahuaPassword","")}catch(e){if(e instanceof ApiError&&e.code==="CAMERA_NAME_ALREADY_EXISTS")setNameError(e.fields?.name?.[0]??e.message);setError(e instanceof ApiError?e.message:"Opslaan mislukt.")}finally{setBusy(false)}};
  if(!form&&!error)return <div className="loading"><span className="spinner"/>Camera laden…</div>;
  const selected=locations.find(item=>item.id===form?.locationId);
  return <><div className="page-header"><div><h1>Camera bewerken</h1><p>Wijzig algemene, locatie- en verbindingsinstellingen.</p></div><button className="button secondary" onClick={()=>router.push("/cameras")}>Terug</button></div>{error?<div className="alert error" role="alert">{error}</div>:null}{success?<div className="alert success" role="status">{success}</div>:null}{form?<form className="card" onSubmit={submit}><div className="form-grid">
    <div className="field"><label htmlFor="camera-name">Cameranaam</label><input id="camera-name" required value={form.name} onChange={e=>set("name",e.target.value)} aria-invalid={Boolean(nameError)}/>{nameError?<small className="field-error">{nameError}</small>:null}</div>
    <div className="field"><label>VPN-locatie</label><select value={form.locationId??""} onChange={e=>selectLocation(e.target.value)}><option value="">Standalone camera</option>{locations.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></div>
    <div className="field"><label>Locatietekst</label><input required value={form.location} onChange={e=>set("location",e.target.value)}/></div><div className="field"><label>Recorder</label><select value={form.recorderId??""} disabled={!selected} onChange={e=>set("recorderId",e.target.value||null)}><option value="">Geen recorder</option>{selected?.recorders.map(recorder=><option key={recorder.id} value={recorder.id}>{recorder.name}</option>)}</select></div>
    <div className="field full"><label>Omschrijving</label><textarea value={form.description??""} onChange={e=>set("description",e.target.value)}/></div><div className="field"><label>Rijrichting</label><select value={form.direction} onChange={e=>set("direction",e.target.value)}><option value="INCOMING">Inkomend</option><option value="OUTGOING">Uitgaand</option><option value="BOTH">Beide</option></select></div><div className="field"><label>Offline-timeout (seconden)</label><input type="number" min="30" max="86400" value={form.offlineTimeoutSeconds} onChange={e=>set("offlineTimeoutSeconds",e.target.value)}/></div>
    <div className="field"><label>Latitude</label><input type="number" step="any" value={form.latitude??""} onChange={e=>set("latitude",e.target.value)}/></div><div className="field"><label>Longitude</label><input type="number" step="any" value={form.longitude??""} onChange={e=>set("longitude",e.target.value)}/></div><label className="checkbox full"><input type="checkbox" checked={form.rtspEnabled} onChange={e=>set("rtspEnabled",e.target.checked)}/>RTSP-videotransport gebruiken</label><div className="field"><label>RTSP-host</label><input disabled={!form.rtspEnabled && form.anprProvider === "NONE"} value={form.rtspHost??""} onChange={e=>set("rtspHost",e.target.value)}/></div><div className="field"><label>RTSP-poort</label><input disabled={!form.rtspEnabled} type="number" min="1" max="65535" value={form.rtspPort} onChange={e=>set("rtspPort",e.target.value)}/></div>
    <div className="field full"><label>Stream/path</label><input disabled={!form.rtspEnabled} value={form.rtspPath??""} onChange={e=>set("rtspPath",e.target.value)}/></div><div className="field"><label>Nieuwe RTSP-gebruikersnaam</label><input disabled={!form.rtspEnabled && form.anprProvider === "NONE"} autoComplete="off" value={form.username} onChange={e=>set("username",e.target.value)} placeholder={form.hasUsername?"Bestaande waarde blijft behouden":"Optioneel"}/></div><div className="field"><label>Nieuw RTSP-wachtwoord</label><input disabled={!form.rtspEnabled && form.anprProvider === "NONE"} type="password" autoComplete="new-password" value={form.password} onChange={e=>set("password",e.target.value)} placeholder={form.hasPassword?"Bestaande waarde blijft behouden":"Optioneel"}/></div>
    <label className="checkbox full"><input type="checkbox" checked={form.dahuaEnabled} onChange={e=>set("dahuaEnabled",e.target.checked)}/>Dahua TCP / SDK-transport gebruiken</label>{form.dahuaEnabled?<><div className="field"><label>Dahua-host</label><input required value={form.dahuaHost} onChange={e=>set("dahuaHost",e.target.value)}/></div><div className="field"><label>TCP-poort</label><input type="number" min="1" max="65535" value={form.dahuaPort} onChange={e=>set("dahuaPort",e.target.value)}/></div><div className="field"><label>Apparaatcategorie</label><select value={form.deviceCategory} onChange={e=>set("deviceCategory",e.target.value)}><option value="AUTO">Automatisch</option><option value="CAMERA">Camera</option><option value="NVR">NVR / Recorder</option></select></div><div/><div className="field"><label>Nieuwe Dahua-gebruikersnaam</label><input autoComplete="off" value={form.dahuaUsername} onChange={e=>set("dahuaUsername",e.target.value)} placeholder={form.hasDahuaUsername?"Bestaande waarde blijft behouden":"Optioneel"}/></div><div className="field"><label>Nieuw Dahua-wachtwoord</label><input type="password" autoComplete="new-password" value={form.dahuaPassword} onChange={e=>set("dahuaPassword",e.target.value)} placeholder={form.hasDahuaPassword?"Bestaande waarde blijft behouden":"Optioneel"}/></div></>:null}
    {form.anprProvider === "DAHUA_CGI" && <NativeAnprTest connection={{ cameraId: id, connectionMode: "FIELDS", rtspHost: form.rtspHost, username: form.username, password: form.password, anprHttpProtocol: form.anprHttpProtocol, anprHttpPort: Number(form.anprHttpPort), anprChannel: Number(form.anprChannel) }} />}
    <div className="field full"><h2>ANPR-events uit de camera</h2><Link className="button secondary" href={`/cameras/${id}/diagnose`}>Diagnose en ITSAPI instellen</Link></div><div className="field"><label>ANPR-provider</label><select value={form.anprProvider} onChange={e=>set("anprProvider",e.target.value)}><option value="DAHUA_ITSAPI">Dahua ITSAPI-upload</option><option value="NONE">Uitgeschakeld</option><option value="DAHUA_CGI">Dahua CGI-eventstream (alternatief)</option></select></div><div className="field"><label>HTTP-protocol</label><select value={form.anprHttpProtocol} onChange={e=>set("anprHttpProtocol",e.target.value)}><option value="http">HTTP</option><option value="https">HTTPS</option></select></div><div className="field"><label>HTTP-poort</label><input type="number" min="1" max="65535" value={form.anprHttpPort} onChange={e=>set("anprHttpPort",e.target.value)}/></div><div className="field"><label>Recorderkanaal</label><input type="number" min="1" max="64" value={form.anprChannel} onChange={e=>set("anprChannel",e.target.value)}/></div>
    <label className="checkbox full"><input type="checkbox" checked={form.active} onChange={e=>set("active",e.target.checked)}/>Camera actief</label></div><div className="alert info">Opgeslagen credentials worden nooit geladen. Laat de geheime velden leeg om ze te behouden.</div>{tcpResult?<DahuaTestStatus result={tcpResult}/>:null}<div className="actions">{form.dahuaEnabled?<button type="button" className="button secondary" disabled={busy} onClick={testTcp}>Dahua TCP/API controleren</button>:null}<button className="button" disabled={busy}>{busy?"Bezig…":"Wijzigingen opslaan"}</button></div></form>:null}</>}
