"use client";
import { FormEvent,useEffect,useState } from "react";
import { useParams,useRouter } from "next/navigation";
import { api,ApiError } from "@/lib/api";
import type { VpnLocation } from "@/lib/locations";

export default function EditLocationPage(){const{id}=useParams<{id:string}>();const router=useRouter();const[form,setForm]=useState<any>();const[error,setError]=useState("");const[busy,setBusy]=useState(false);useEffect(()=>{api<{location:VpnLocation}>(`/locations/${id}`).then(({location})=>setForm({...location,recorder:location.recorders[0]?{...location.recorders[0],rtspPort:String(location.recorders[0].rtspPort),channelCount:location.recorders[0].channelCount?String(location.recorders[0].channelCount):""}:undefined})).catch(e=>setError(e.message))},[id]);const set=(key:string,value:any)=>setForm((current:any)=>({...current,[key]:value}));const setRecorder=(key:string,value:string)=>setForm((current:any)=>({...current,recorder:{...(current.recorder??{name:"Recorder",ipAddress:"",rtspPort:"554",channelCount:""}),[key]:value}}));
  const submit=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setError("");try{await api(`/locations/${id}`,{method:"PATCH",body:JSON.stringify({name:form.name,description:form.description||undefined,routerType:form.routerType,vpnType:"WIREGUARD",vpnMode:form.vpnMode,remoteLanCidr:form.remoteLanCidr,remoteGatewayIp:form.remoteGatewayIp||undefined,endpointHost:form.endpointHost||undefined,listenPort:Number(form.listenPort),mtu:Number(form.mtu),active:form.active,recorder:form.recorder?.ipAddress?{name:form.recorder.name,ipAddress:form.recorder.ipAddress,rtspPort:Number(form.recorder.rtspPort),channelCount:form.recorder.channelCount?Number(form.recorder.channelCount):undefined}:undefined})});router.push(`/locations/${id}`)}catch(e){setError(e instanceof ApiError?e.message:"Locatie opslaan mislukt.")}finally{setBusy(false)}};
  if(!form&&!error)return <div className="loading"><span className="spinner"/>Locatie laden…</div>;
  return <><div className="page-header"><div><h1>Locatie bewerken</h1><p>Tunnel-IP en private keys wijzigen niet via dit formulier.</p></div></div>{error?<div className="alert error" role="alert">{error}</div>:null}{form?<form className="card" onSubmit={submit}><div className="form-grid"><div className="field"><label>Locatienaam</label><input required value={form.name} onChange={e=>set("name",e.target.value)}/></div><div className="field"><label>Routertype</label><select value={form.routerType} onChange={e=>set("routerType",e.target.value)}><option value="TP_LINK_OMADA_ER605">TP-Link Omada ER605</option><option value="MANUAL_OTHER">Handmatig / Andere router</option></select></div><div className="field full"><label>Omschrijving</label><textarea value={form.description??""} onChange={e=>set("description",e.target.value)}/></div><div className="field"><label>Remote LAN subnet</label><input required value={form.remoteLanCidr} onChange={e=>set("remoteLanCidr",e.target.value)}/></div><div className="field"><label>Router LAN IP</label><input value={form.remoteGatewayIp??""} onChange={e=>set("remoteGatewayIp",e.target.value)}/></div><div className="field"><label>VPN-modus</label><select value={form.vpnMode} onChange={e=>set("vpnMode",e.target.value)}><option value="LOCATION_TO_SERVER">ER605 → centraal</option><option value="SERVER_TO_LOCATION">Centraal → ER605</option></select></div><div className="field"><label>Centraal endpoint</label><input value={form.endpointHost??""} onChange={e=>set("endpointHost",e.target.value)}/></div><div className="field"><label>Listen Port</label><input type="number" min="1" max="65535" value={form.listenPort} onChange={e=>set("listenPort",e.target.value)}/></div><div className="field"><label>MTU</label><input type="number" min="576" max="1440" value={form.mtu} onChange={e=>set("mtu",e.target.value)}/></div><div className="field"><label>Recordernaam</label><input value={form.recorder?.name??""} onChange={e=>setRecorder("name",e.target.value)}/></div><div className="field"><label>Recorder IP</label><input value={form.recorder?.ipAddress??""} onChange={e=>setRecorder("ipAddress",e.target.value)}/></div><div className="field"><label>RTSP-poort</label><input type="number" min="1" max="65535" value={form.recorder?.rtspPort??"554"} onChange={e=>setRecorder("rtspPort",e.target.value)}/></div><div className="field"><label>Aantal kanalen</label><input type="number" min="1" max="256" value={form.recorder?.channelCount??""} onChange={e=>setRecorder("channelCount",e.target.value)}/></div><label className="checkbox full"><input type="checkbox" checked={form.active} onChange={e=>set("active",e.target.checked)}/>Locatie actief</label></div><div className="actions"><button type="button" className="button secondary" onClick={()=>router.push(`/locations/${id}`)}>Annuleren</button><button className="button" disabled={busy}>{busy?"Opslaan…":"Wijzigingen opslaan"}</button></div></form>:null}</>}
