export type DiagnosticStatus = "NOT_CONFIGURED" | "NOT_TESTED" | "RUNNING" | "WAITING_CAMERA" | "WAITING_PASSAGE" | "SUCCESS" | "WARNING" | "FAILED" | "UNSUPPORTED" | "DISABLED" | "STALE";
export type DiagnosticCheck = {
  checkId: string; title: string; direction: string; status: DiagnosticStatus;
  checkedAt: string | null; lastSuccessAt: string | null; configVersion: number;
  evidence: string[]; errorCode: string | null; message: string;
  possibleCauses: string[]; suggestedActions: string[];
};
const date = (x: Date | string | null | undefined) => x ? new Date(x).toISOString() : null;
export function cameraDiagnostics(camera: any, registration: any, receiverActive: boolean, now = new Date(), latestPassage?: {createdAt:Date; vehicleImage1ObjectId:string|null; plateImageObjectId:string|null; vehicleImage2ObjectId:string|null; hits:Array<{notificationStatus:string}>} | null): DiagnosticCheck[] {
  const version = camera.configVersion;
  const check = (checkId: string,title: string,direction: string,status: DiagnosticStatus,message: string,actions: string[],extra: Partial<DiagnosticCheck> = {}): DiagnosticCheck => ({checkId,title,direction,status,checkedAt:null,lastSuccessAt:null,configVersion:version,evidence:[],errorCode:null,message,possibleCauses:[],suggestedActions:actions,...extra});
  const video = camera.videoTest;
  const staleVideo = video && (camera.videoTestVersion !== version || now.getTime()-new Date(camera.videoTestAt).getTime() > 30*60_000);
  const videoStatus: DiagnosticStatus = !camera.rtspEnabled ? "DISABLED" : !video ? "NOT_TESTED" : staleVideo ? "STALE" : video.success ? "SUCCESS" : "FAILED";
  const pending = camera.anprProvider !== "DAHUA_ITSAPI" ? "DISABLED" : !registration ? "NOT_CONFIGURED" : "WAITING_CAMERA";
  const currentEvidence = registration?.evidenceVersion === version;
  const authenticated = currentEvidence && registration?.lastAuthenticatedAt;
  const identity = currentEvidence && registration?.lastIdentityAt;
  const heartbeat = currentEvidence && registration?.lastHeartbeatAt;
  const heartbeatStale = heartbeat && now.getTime()-new Date(heartbeat).getTime() > (registration.heartbeatSeconds*2+30)*1000;
  const cgiEvidence=camera.anprProvider==="DAHUA_CGI"?latestPassage:null;
  const evidenceAt=date(cgiEvidence?.createdAt);
  return [
    check("video","Video ontvangen en decoderen","Platform → camera",videoStatus,videoStatus === "STALE" ? "Resultaat hoort bij een oudere configuratie of is ouder dan 30 minuten." : video?.rtspVideo?.message ?? "Nog geen nieuw videoframe getest.",["Klik Beeld testen; controleer bij fouten host, RTSP-poort, stream en camera-inlog."],{checkedAt:date(camera.videoTestAt),lastSuccessAt:date(camera.lastConnectionSuccessAt),evidence:video?.success?["FFmpeg heeft via een nieuwe RTSP-over-TCP-sessie een JPEG-frame gedecodeerd."]:[],errorCode:video?.success?null:video?.code??null,possibleCauses:video && !video.success?["Verkeerde camera-inlog", "Onjuist streamadres", "Netwerkroute of videocodec"]:[]}),
    check("snapshot","Nieuw snapshot","Platform → camera",staleVideo?"STALE":!video?"NOT_TESTED":!video.success?"NOT_TESTED":video.snapshot?.status==="AVAILABLE"?"SUCCESS":"WARNING",!video?.success?"Niet uitgevoerd zonder geslaagde videodecodering.":video.snapshot?.message??"Geen nieuw beeld opgeslagen.",["Haal een nieuw beeld op; oude snapshots zijn geen bewijs van deze test."],{checkedAt:date(camera.videoTestAt),lastSuccessAt:date(video?.snapshotAt),evidence:video?.snapshotAt?[`Nieuw beeld van ${video.snapshotAt}`]:[],errorCode:video && !video.success?"DEPENDENCY_FAILED":video?.snapshot?.code??null}),
    check("cgi","Aanvullende CGI-eventstream","Platform → camera",camera.anprProvider==="DAHUA_CGI" ? camera.anprConnectionStatus==="CONNECTED"?"WARNING":"NOT_TESTED":"DISABLED",camera.anprProvider==="DAHUA_CGI"?"Bestaand CGI-alternatief. Een geopende stream bewijst geen ITSAPI-upload of kentekenpassage.":"CGI is optioneel en blokkeert ITSAPI niet.",["Behoud CGI alleen wanneer je bewust dit bestaande alternatief gebruikt."]),
    check("receiver","ITSAPI-ontvanger intern","Binnen platform",receiverActive?"SUCCESS":"FAILED",receiverActive?"De gedeelde ontvanger en database reageren intern. Dit bewijst geen verbinding vanuit de camera.":"De ontvanger reageert intern niet.",["Controleer Docker-publicatie en het door de camera bereikbare LAN-/VPN-adres."],{checkedAt:now.toISOString(),evidence:receiverActive?["Interne /health-respons van itsapi-receiver gecontroleerd."]:[],errorCode:receiverActive?null:"RECEIVER_UNAVAILABLE"}),
    check("upload_identity","ITSAPI-identiteit en authenticatie","Camera → platform",pending==="DISABLED"?"DISABLED":currentEvidence && registration?.lastErrorCode==="UPLOAD_AUTH_FAILED"?"FAILED":identity?"SUCCESS":authenticated?"WARNING":pending,identity?"Camera-identiteit en uploadauthenticatie bevestigd.":authenticated?"Uploadcredentials gecontroleerd; Device ID en berichtformaat nog niet geverifieerd.":"Wachten op verbinding vanuit de camera.",["Neem het bevestigde ontvangstadres en de afzonderlijke uploadinlog over in de camera.","Controleer de Device ID en lever de firmware-specifieke ITSAPI-protocolinformatie aan."],{checkedAt:date(registration?.lastRequestAt),lastSuccessAt:date(identity),errorCode:registration?.lastErrorCode??null,evidence:authenticated?["Digest-handtekening gecontroleerd; dit is geen bewijs van een geldig heartbeat- of ANPR-bericht."]:[],possibleCauses:!authenticated?["ITSAPI nog niet ingesteld in de camera", "Onjuist ontvangstadres", "Uploadinlog, routering of gerichte firewalltoegang"]:[]}),
    check("registration","ITSAPI-registratie","Camera → platform",pending==="DISABLED"?"DISABLED":!registration?"NOT_CONFIGURED":"NOT_TESTED","Registration staat op de camera aan; registratiepad en berichtformaat zijn nog niet bevestigd.",["Behoud de bestaande Device ID. Een geldige uploadinlog bewijst nog geen geslaagde cameraregistratie."],{errorCode:pending==="DISABLED"?null:"REGISTRATION_PROTOCOL_UNVERIFIED"}),
    check("heartbeat","Geldige heartbeat","Camera → platform",pending==="DISABLED"?"DISABLED":heartbeat?heartbeatStale?"STALE":"SUCCESS":pending,"Een ontvangen onbekend bericht geldt niet als geldige heartbeat.",["Controleer het heartbeatinterval op camera en platform; verstrek het werkelijke heartbeatverzoek als het formaat onbekend is."],{checkedAt:date(heartbeat),lastSuccessAt:date(heartbeat),evidence:[`Bewaking volgt ingesteld interval: ${registration?.heartbeatSeconds??300} s, met marge.`]}),
    check("event","Echte passageontvangst","Camera → platform",pending==="DISABLED"?"DISABLED":currentEvidence&&registration?.lastEventAt?"SUCCESS":identity?"WAITING_PASSAGE":"NOT_TESTED","Nog geen geverifieerd ITSAPI-passagebericht. Geen verkeer bewijst geen defect.",["Laat na een geldige cameraverbinding één voertuig herkennen; controleer eerst of de camera zelf de passage registreert."],{lastSuccessAt:date(currentEvidence?registration?.lastEventAt:null)}),
    check("parser","ITSAPI-parser en bevestiging","Binnen platform",pending==="DISABLED"?"DISABLED":"UNSUPPORTED","Firmware-specifieke payloadmapping en bevestigingsresponse zijn nog niet bewezen.",["Nodig: echte heartbeat en ANPR-request (pad, methode, geschoonde JSON), beeldcodering en officiële bevestigingsspecificatie."],{errorCode:"PROTOCOL_NOT_VERIFIED"}),
    ...[ ["images","Gebeurtenisbeelden"],["database","Passageopslag"],["watchlist","Watchlistverwerking"],["push","Pushmelding"] ].map(([id,title])=>{
      if(!cgiEvidence)return check(id!,title!,"Binnen platform","NOT_TESTED",camera.anprProvider==="DAHUA_CGI"?"Nog geen opgeslagen CGI-passage aangetroffen.":"Niet uitgevoerd: nog geen geverifieerde ITSAPI-passage.",["Test een echte passage met de gekozen koppeling; ontbrekende optionele beelden blokkeren geen passage."]);
      const hit=cgiEvidence.hits[0];
      const images=[cgiEvidence.vehicleImage1ObjectId,cgiEvidence.plateImageObjectId,cgiEvidence.vehicleImage2ObjectId];
      const status:DiagnosticStatus=id==="database"?"SUCCESS":id==="images"?images.every(Boolean)?"SUCCESS":"WARNING":id==="watchlist"?hit?"SUCCESS":"NOT_TESTED":hit?.notificationStatus==="SENT"?"SUCCESS":hit?.notificationStatus==="FAILED"?"FAILED":"NOT_TESTED";
      const message=id==="database"?"Een echte CGI-passage is opgeslagen.":id==="images"?`Opgeslagen bij die passage: overzicht ${images[0]?"ja":"nee"}, kentekenuitsnede ${images[1]?"ja":"nee"}, voertuiguitsnede ${images[2]?"ja":"nee"}.`:id==="watchlist"?hit?"Een Hit is gekoppeld aan die passage.":"Die passage heeft geen Hit; dat bewijst geen fout in matching.":hit?`Pushstatus van die Hit: ${hit.notificationStatus}. SENT betekent aangeboden aan de pushdienst; toestelontvangst apart controleren.`:"Geen Hit bij die passage om push te beoordelen.";
      return check(id!,title!,"Binnen platform",status,message,["Dit is opgeslagen CGI-historie, geen bewijs voor de huidige configuratie of ITSAPI. Test na wijzigingen een nieuwe passage."],{checkedAt:now.toISOString(),lastSuccessAt:status==="SUCCESS"?evidenceAt:null,evidence:[`Laatste opgeslagen CGI-passage ontvangen op ${evidenceAt}`]});
    }),
  ];
}
