"use client";
import Link from "next/link";
import { useCallback,useEffect,useState } from "react";
import { useParams,useRouter } from "next/navigation";
import { PERMISSIONS } from "@anpr/shared";
import { api,ApiError,formatDate } from "@/lib/api";
import { locationStatusColors,locationStatusLabels,routerLabels,type VpnLocation } from "@/lib/locations";

type Configuration={location:{interfaceName:string;privateKey?:string;publicKey:string;localIpAddress:string;mtu:number;listenPort:number};peer:{publicKey:string;allowedAddress:string;endpoint?:string|null;endpointPort:number;persistentKeepalive:number};central:{publicKey:string;address:string;allowedIps:string[]};privateKeyNotice:string};
function Value({label,value}:{label:string;value:string|number|null|undefined}){const copy=()=>value!==null&&value!==undefined&&navigator.clipboard.writeText(String(value));return <div className="config-value"><span>{label}</span><code>{value||'Niet ingesteld'}</code>{value?<button className="button secondary" onClick={copy}>Kopiëren</button>:null}</div>}

export default function LocationDetailPage(){const{id}=useParams<{id:string}>();const router=useRouter();const[location,setLocation]=useState<VpnLocation>();const[canManage,setCanManage]=useState(false);const[configuration,setConfiguration]=useState<Configuration>();const[error,setError]=useState("");const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{try{const[data,me]=await Promise.all([api<{location:VpnLocation}>(`/locations/${id}`,{cache:'no-store'}),api<{user:{permissions:string[]}}>('/auth/me')]);setLocation(data.location);setCanManage(me.user.permissions.includes(PERMISSIONS.LOCATIONS_MANAGE));}catch(e){setError(e instanceof Error?e.message:"Locatie ophalen mislukt.");}},[id]);useEffect(()=>{void load()},[load]);
  const generate=async()=>{setBusy(true);setError("");try{const data=await api<{configuration:Configuration}>(`/locations/${id}/wireguard-config`,{method:'POST'});setConfiguration(data.configuration);setMessage(data.configuration.privateKeyNotice);}catch(e){setError(e instanceof ApiError?e.message:"Configuratie genereren mislukt.");}finally{setBusy(false)}};
  const test=async()=>{setBusy(true);setError("");try{const data=await api<{location:VpnLocation}>(`/locations/${id}/test`,{method:'POST'});setLocation(data.location);setMessage("Verbindingstest afgerond. Onbekend betekent dat de host-statusadapter nog niet is ingesteld.");}catch(e){setError(e instanceof ApiError?e.message:"Verbindingstest mislukt.");}finally{setBusy(false)}};
  const remove=async()=>{if(!location||!window.confirm(`Locatie '${location.name}' verwijderen?`))return;setBusy(true);try{await api(`/locations/${id}`,{method:'DELETE'});router.push('/locations');}catch(e){setError(e instanceof ApiError?e.message:"Verwijderen mislukt.");}finally{setBusy(false)}};
  if(!location&&!error)return <div className="loading"><span className="spinner"/>Locatie laden…</div>;
  return <>{error?<div className="alert error" role="alert">{error}</div>:null}{location?<><div className="page-header"><div><h1>{location.name}</h1><p>{routerLabels[location.routerType]} · {location.remoteLanCidr}</p></div><span className={`badge ${locationStatusColors[location.connectionStatus]??'gray'}`}>{locationStatusLabels[location.connectionStatus]??location.connectionStatus}</span></div>{message?<div className="alert info" role="status">{message}</div>:null}<div className="grid-2"><section className="card"><h2>Verbindingsstatus</h2><div className="status-list"><div className="status-row"><div><strong>VPN tunnel</strong><small>Handshake via optionele host-adapter</small></div><span className={`badge ${location.tunnelOnline===true?'green':location.tunnelOnline===false?'red':'gray'}`}>{location.tunnelOnline===true?'Online':location.tunnelOnline===false?'Offline':'Onbekend'}</span></div><div className="status-row"><div><strong>Laatste handshake</strong><small>{formatDate(location.lastHandshakeAt)}</small></div></div><div className="status-row"><div><strong>Remote LAN route</strong></div><span>{location.routeReachable===true?'Bereikbaar':location.routeReachable===false?'Niet bereikbaar':'Onbekend'}</span></div><div className="status-row"><div><strong>Recorder</strong><small>{location.recorders[0]?.ipAddress??'Niet ingesteld'}</small></div><span>{location.recorderReachable===true?'Bereikbaar':location.recorderReachable===false?'Niet bereikbaar':'Onbekend'}</span></div><div className="status-row"><div><strong>RTSP-poort {location.recorders[0]?.rtspPort??554}</strong></div><span>{location.recorderPortOpen===true?'Open':location.recorderPortOpen===false?'Gesloten / timeout':'Onbekend'}</span></div></div>{canManage?<div className="actions"><button className="button" disabled={busy} onClick={test}>{busy?'Testen…':'VPN-verbinding testen'}</button></div>:null}</section><section className="card"><h2>Adresplan</h2><div className="detail-list"><div><span>Tunnel-IP</span><strong>{location.tunnelAddress}</strong></div><div><span>Remote LAN</span><strong>{location.remoteLanCidr}</strong></div><div><span>Router LAN IP</span><strong>{location.remoteGatewayIp??'Niet ingesteld'}</strong></div><div><span>Modus</span><strong>{location.vpnMode==='LOCATION_TO_SERVER'?'ER605 → centraal':'Centraal → ER605'}</strong></div><div><span>Laatste controle</span><strong>{formatDate(location.lastCheckedAt)}</strong></div><div><span>Camera’s</span><strong>{location.cameras?.length??location._count?.cameras??0}</strong></div></div></section></div>
  <section className="card" style={{marginTop:20}}><h2>ER605 instellen</h2><p className="subtitle">De app logt niet in op de router. Neem onderstaande waarden handmatig over.</p>{canManage?<button className="button" disabled={busy} onClick={generate}>WireGuard-configuratie genereren</button>:null}{configuration?<div className="er605-steps"><div><h3>1. VPN → WireGuard → WireGuard → Add</h3><Value label="Name" value={configuration.location.interfaceName}/><Value label="MTU" value={configuration.location.mtu}/><Value label="Listen Port" value={configuration.location.listenPort}/><Value label="Private Key (eenmalig zichtbaar)" value={configuration.location.privateKey}/><Value label="Public Key locatie" value={configuration.location.publicKey}/><Value label="Local IP Address" value={configuration.location.localIpAddress}/><Value label="Status" value="Enable"/></div><div><h3>2. VPN → WireGuard → Peers → Add</h3><Value label="Interface" value={configuration.location.interfaceName}/><Value label="Public Key" value={configuration.peer.publicKey}/><Value label="Allowed Address" value={configuration.peer.allowedAddress}/><Value label="Endpoint" value={configuration.peer.endpoint}/><Value label="Endpoint Port" value={configuration.peer.endpointPort}/><Value label="Persistent Keepalive" value={`${configuration.peer.persistentKeepalive} seconden`}/><Value label="Status" value="Enable"/></div><div className="alert info"><strong>Centrale peerconfiguratie:</strong> AllowedIPs {configuration.central.allowedIps.join(', ')}. De centrale private key blijft uitsluitend versleuteld op de server.</div></div>:<div className="alert info">Genereer de configuratie pas wanneer u klaar bent om de eenmalig zichtbare locatie-private key direct naar de ER605 te kopiëren.</div>}</section>
  <section className="card" style={{marginTop:20}}><h2>Recorder en kanalen</h2>{location.recorders.map(recorder=><div key={recorder.id} className="status-row"><div><strong>{recorder.name}</strong><small>{recorder.ipAddress}:{recorder.rtspPort} · {recorder.channelCount??'onbekend'} kanalen</small></div>{canManage?<div className="inline-actions">{Array.from({length:Math.min(recorder.channelCount??2,16)},(_,index)=><Link key={index} className="button secondary" href={`/cameras/new?locationId=${location.id}&recorderId=${recorder.id}&host=${recorder.ipAddress}&port=${recorder.rtspPort}&channel=${index+1}`}>Kanaal {index+1}</Link>)}</div>:null}</div>)}{!location.recorders.length?<p>Geen recorder ingesteld.</p>:null}</section>{canManage?<div className="actions"><Link className="button secondary" href={`/locations/${location.id}/edit`}>Locatie bewerken</Link><button className="button danger" disabled={busy} onClick={remove}>Locatie verwijderen</button></div>:null}</>:null}</>}
