"use client";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { api, ApiError, formatDate } from "@/lib/api";
import { Icon } from "@/components/icons";

type Camera={id:string;isDraft:boolean;name:string;location:string;description?:string;direction:string;status:string;active:boolean;lastConnectionAt?:string;lastVehicleRegistrationAt?:string;lastSnapshotObjectId?:string;anprProvider:string;anprConnectionStatus:string;_count:{passages:number}};
const statusLabel:Record<string,string>={ONLINE:"Online",OFFLINE:"Offline",CONNECTION_PROBLEM:"Verbindingsprobleem",ANPR_UNAVAILABLE:"ANPR niet beschikbaar",DISABLED:"Uitgeschakeld"};
const direction:Record<string,string>={INCOMING:"Inkomend",OUTGOING:"Uitgaand",BOTH:"Beide"};
export default function Cameras(){const[cameras,setCameras]=useState<Camera[]>([]);const[error,setError]=useState("");const[busy,setBusy]=useState("");const[admin,setAdmin]=useState(false);const deleting=useRef(new Set<string>());
  const load=()=>api<{cameras:Camera[]}>("/cameras",{cache:"no-store"}).then(d=>setCameras(d.cameras)).catch(e=>setError(e.message));useEffect(()=>{void load();void api<{user:{roles:string[]}}>("/auth/me").then(r=>setAdmin(r.user.roles.some(role=>role==="ADMIN"||role==="Administrator"))).catch(()=>{})},[]);
  const toggle=async(c:Camera)=>{setBusy(c.id);setError("");try{await api(`/cameras/${c.id}`,{method:"PATCH",body:JSON.stringify({active:!c.active})});await load();}catch(e){setError(e instanceof ApiError?e.message:"Wijzigen mislukt.");}finally{setBusy("");}};
  const test=async(c:Camera)=>{setBusy(c.id);setError("");try{const r=await api<any>(`/cameras/${c.id}/test`,{method:"POST"});if(!r.success)setError(r.message);await load();}catch(e){setError(e instanceof ApiError?e.message:"Test mislukt.");}finally{setBusy("");}};
  const remove=async(c:Camera)=>{if(deleting.current.has(c.id)||!confirm(`Weet je zeker dat je deze camera wilt verwijderen?\n\n${c.name}: verbindingen en zones worden verwijderd. Historische passages en hits blijven behouden. Uploadtoegang wordt ingetrokken. Schakel ITSAPI daarna zelf uit op de fysieke camera.`))return;deleting.current.add(c.id);setBusy(c.id);setError("");try{await api(`/cameras/${c.id}`,{method:"DELETE"});setCameras(current=>current.filter(item=>item.id!==c.id));await load();}catch(e){setError(e instanceof ApiError?e.message:"Verwijderen mislukt.");await load();}finally{deleting.current.delete(c.id);setBusy("");}};
  return <><div className="page-header"><div><h1>Camera’s</h1><p>Beheer camera’s en controleer beeld en kentekengegevens afzonderlijk.</p></div><Link className="button" href="/cameras/new"><Icon name="plus"/>Camera toevoegen</Link></div>{error&&<div className="alert error">{error}</div>}<div className="camera-grid">{cameras.map(c=><article className="card camera-card" key={c.id}><div className="camera-preview">{c.lastSnapshotObjectId?<img src={`/api/cameras/${c.id}/snapshot`} alt={`Snapshot ${c.name}`}/>:<span>Geen snapshot beschikbaar</span>}<span className={`badge ${c.status==="ONLINE"?"green":c.status==="DISABLED"?"gray":"red"}`}><span className="dot"/>{statusLabel[c.status]??c.status}</span></div><div className="camera-body"><h2>{c.name}</h2>{c.isDraft&&<span className="badge gray">Concept</span>}<p>{c.location}</p><div className="camera-meta"><div><span>Rijrichting</span>{direction[c.direction]}</div><div><span>Passages 24 uur</span>{c._count.passages}</div><div><span>Laatste verbinding</span>{formatDate(c.lastConnectionAt)}</div><div><span>Laatste registratie</span>{formatDate(c.lastVehicleRegistrationAt)}</div><div><span>ANPR-events</span>{c.anprProvider==="NONE"?"Uitgeschakeld":c.anprProvider==="DAHUA_ITSAPI"?"ITSAPI – zie diagnose":c.anprConnectionStatus}</div></div><div className="camera-actions"><Link className="button secondary" href={c.isDraft?`/cameras/new?draft=${c.id}`:`/cameras/${c.id}`}>{c.isDraft?"Hervatten":"Bewerken"}</Link><Link className="button secondary" href={`/cameras/${c.id}/diagnose`}>Diagnose</Link><button className="button secondary" disabled={busy===c.id} onClick={()=>test(c)}>Test</button><button className="button secondary" disabled={busy===c.id||c.isDraft} onClick={()=>toggle(c)}>{c.active?"Uit":"Aan"}</button>{admin&&<button className="button danger" aria-label="Verwijderen" disabled={busy===c.id} onClick={()=>remove(c)}><Icon name="trash"/></button>}</div></div></article>)}</div>{!cameras.length&&!error&&<div className="card empty">Er zijn nog geen camera’s. Voeg de eerste camera toe met de wizard.</div>}</>}
