"use client";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import { api, formatDate } from "@/lib/api";

type Passage={id:string;displayLicensePlate:string;plateConfidence?:number|null;plateCountry?:string|null;timestamp:string;location:string;direction:string;vehicleColor:string;vehicleType:string;vehicleBrand?:string|null;lane?:number|null;source:string;vehicleImage1ObjectId?:string|null;plateImageObjectId?:string|null;camera:{name:string;location:string}};
const labels:Record<string,string>={INCOMING:"Inkomend",OUTGOING:"Uitgaand",BOTH:"Beide",DAHUA_CAMERA:"Dahua camera-ANPR",DEMO:"DEMO / simulator",SERVER_OCR:"Server-OCR",ANPR:"ANPR",MANUAL:"Handmatig"};
export default function PassageDetail(){const{id}=useParams<{id:string}>();const[data,setData]=useState<Passage>();const[error,setError]=useState("");useEffect(()=>{api<{passage:Passage}>(`/passages/${id}`,{cache:"no-store"}).then(r=>setData(r.passage)).catch(e=>setError(e.message))},[id]);if(error)return <><Link className="button secondary" href="/passages">Terug</Link><div className="alert error">{error}</div></>;if(!data)return <div className="loading"><span className="spinner"/>Passage laden…</div>;const rows:Array<[string,string|number|undefined|null]>=[["Kenteken",data.displayLicensePlate],["Camera",data.camera.name],["Locatie",data.location],["Datum en tijd",formatDate(data.timestamp)],["Kleur",data.vehicleColor!=="UNKNOWN"?data.vehicleColor:null],["Voertuigtype",data.vehicleType!=="UNKNOWN"?data.vehicleType:null],["Merk",data.vehicleBrand],["Confidence",data.plateConfidence!=null?`${Math.round(data.plateConfidence*100)}%`:null],["Rijrichting",labels[data.direction]??data.direction],["Lane",data.lane],["Land/regio",data.plateCountry],["Detectiebron",labels[data.source]??data.source]];return <><div className="page-header"><div><h1>Passage {data.displayLicensePlate}</h1><p>Details van één afzonderlijke camerawaarneming.</p></div><Link className="button secondary" href="/passages">Terug naar passages</Link></div>{data.source==="DEMO"&&<div className="demo-banner">Dit is een DEMO-passage en geen echte ANPR-detectie.</div>}<div className="passage-detail-grid"><section className="card"><h2>Overzichtsfoto</h2><div className="detail-image">{data.vehicleImage1ObjectId?<img src={`/api/passages/${data.id}/image/overview`} alt="Overzichtsfoto voertuig"/>:<span>Niet beschikbaar</span>}</div></section><section className="card"><h2>Kentekenfoto</h2><div className="detail-image plate">{data.plateImageObjectId?<img src={`/api/passages/${data.id}/image/plate`} alt="Kentekenfoto"/>:<span>Niet beschikbaar</span>}</div></section></div><section className="card" style={{marginTop:18}}><h2>Registratiegegevens</h2><div className="detail-list">{rows.filter(([,value])=>value!==null&&value!==undefined&&value!=="").map(([name,value])=><div key={name}><span>{name}</span><strong>{value}</strong></div>)}</div></section></>}
