"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { api,ApiError } from "@/lib/api";

const initial={name:"",description:"",routerType:"TP_LINK_OMADA_ER605",remoteLanCidr:"192.168.178.0/24",remoteGatewayIp:"192.168.178.1",recorderIp:"192.168.178.210",recorderName:"Hoofdrecorder",rtspPort:"554",channelCount:"2",endpointHost:"",vpnMode:"LOCATION_TO_SERVER",active:true};
export default function NewLocationPage(){const router=useRouter();const[step,setStep]=useState(1);const[form,setForm]=useState(initial);const[error,setError]=useState("");const[busy,setBusy]=useState(false);const set=(key:string,value:string|boolean)=>setForm(current=>({...current,[key]:value}));
  const next=()=>{if(step===1&&!form.name.trim()){setError("Vul een locatienaam in.");return}setError("");setStep(current=>Math.min(4,current+1));};
  const save=async()=>{setBusy(true);setError("");try{const response=await api<{location:{id:string}}>("/locations",{method:"POST",body:JSON.stringify({name:form.name,description:form.description||undefined,routerType:form.routerType,vpnType:"WIREGUARD",vpnMode:form.vpnMode,remoteLanCidr:form.remoteLanCidr,remoteGatewayIp:form.remoteGatewayIp||undefined,endpointHost:form.endpointHost||undefined,listenPort:51820,mtu:1420,active:form.active,recorder:form.recorderIp?{name:form.recorderName||"Recorder",ipAddress:form.recorderIp,rtspPort:Number(form.rtspPort),channelCount:form.channelCount?Number(form.channelCount):undefined}:undefined})});router.push(`/locations/${response.location.id}`);}catch(e){setError(e instanceof ApiError?e.message:"Locatie opslaan mislukt.");}finally{setBusy(false)}};
  const labels=["Naam","Router","Netwerk","Controleren"];
  return <div className="wizard"><div className="page-header"><div><h1>VPN-locatie toevoegen</h1><p>De wizard configureert niets automatisch op de router.</p></div></div><div className="steps">{labels.map((label,index)=><div className={`step ${step===index+1?'active':step>index+1?'done':''}`} key={label}><div className="step-number">{step>index+1?'✓':index+1}</div><span className="step-label">{label}</span></div>)}</div><section className="card wizard-card">{error?<div className="alert error" role="alert">{error}</div>:null}
  {step===1?<><h2>Naam</h2><div className="form-grid"><div className="field"><label htmlFor="location-name">Locatienaam *</label><input id="location-name" value={form.name} onChange={e=>set('name',e.target.value)} placeholder="Uddel Noord"/></div><div className="field full"><label htmlFor="description">Omschrijving</label><textarea id="description" value={form.description} onChange={e=>set('description',e.target.value)}/></div></div></>:null}
  {step===2?<><h2>Router</h2><div className="mode-select"><button className={form.routerType==='TP_LINK_OMADA_ER605'?'active':''} onClick={()=>set('routerType','TP_LINK_OMADA_ER605')}><strong>TP-Link Omada ER605</strong><span>Handmatige WireGuard-configuratie</span></button><button className={form.routerType==='MANUAL_OTHER'?'active':''} onClick={()=>set('routerType','MANUAL_OTHER')}><strong>Handmatig / Andere router</strong><span>Generieke WireGuard-waarden</span></button></div><div className="alert info">Deze wizard gaat uit van ER605 V2 of nieuwer met recente firmware en WireGuard-ondersteuning.</div><div className="field"><label>VPN-modus</label><select value={form.vpnMode} onChange={e=>set('vpnMode',e.target.value)}><option value="LOCATION_TO_SERVER">ER605 verbindt uitgaand met centrale server (aanbevolen)</option><option value="SERVER_TO_LOCATION">Centrale server verbindt met ER605</option></select></div></>:null}
  {step===3?<><h2>Netwerkgegevens</h2><div className="form-grid"><div className="field"><label>Remote LAN subnet *</label><input value={form.remoteLanCidr} onChange={e=>set('remoteLanCidr',e.target.value)} placeholder="192.168.178.0/24"/><small>Elke locatie moet een uniek, niet-overlappend subnet hebben.</small></div><div className="field"><label>Router LAN IP</label><input value={form.remoteGatewayIp} onChange={e=>set('remoteGatewayIp',e.target.value)} placeholder="192.168.178.1"/></div><div className="field"><label>Recordernaam</label><input value={form.recorderName} onChange={e=>set('recorderName',e.target.value)}/></div><div className="field"><label>Recorder IP</label><input value={form.recorderIp} onChange={e=>set('recorderIp',e.target.value)} placeholder="192.168.178.210"/></div><div className="field"><label>RTSP-poort</label><input type="number" min="1" max="65535" value={form.rtspPort} onChange={e=>set('rtspPort',e.target.value)}/></div><div className="field"><label>Aantal kanalen (optioneel)</label><input type="number" min="1" max="256" value={form.channelCount} onChange={e=>set('channelCount',e.target.value)}/></div><div className="field full"><label>Centraal publiek endpoint (optioneel)</label><input value={form.endpointHost} onChange={e=>set('endpointHost',e.target.value)} placeholder="vpn.voorbeeld.nl of publiek IP"/><small>Dit kan later centraal worden gewijzigd. Een lokale WSL/Docker-server is normaal niet vanzelf publiek bereikbaar.</small></div></div><div className="alert info"><strong>Centrale server draait lokaal?</strong> Configureer router/firewall/NAT dan bewust en handmatig. Deze wizard opent geen poorten, gebruikt geen UPnP en omzeilt geen firewall.</div></>:null}
  {step===4?<><h2>Controleren</h2><div className="summary"><div><span>Locatie</span><strong>{form.name}</strong></div><div><span>Router</span><strong>{form.routerType==='TP_LINK_OMADA_ER605'?'TP-Link Omada ER605':'Handmatig / Andere router'}</strong></div><div><span>Remote LAN</span><strong>{form.remoteLanCidr}</strong></div><div><span>Recorder</span><strong>{form.recorderIp||'Niet ingesteld'}:{form.rtspPort}</strong></div><div><span>VPN-modus</span><strong>{form.vpnMode==='LOCATION_TO_SERVER'?'Locatie → centraal':'Centraal → locatie'}</strong></div></div><label className="checkbox"><input type="checkbox" checked={form.active} onChange={e=>set('active',e.target.checked)}/>Locatie actief maken</label><div className="alert info">Na opslaan krijgt de locatie automatisch een uniek tunnel-IP. Daarna opent de concrete ER605-instructie.</div></>:null}
  <div className="actions wizard-navigation">{step>1?<button className="button secondary" onClick={()=>setStep(current=>current-1)}>Vorige</button>:null}{step<4?<button className="button" onClick={next}>Volgende</button>:<button className="button" disabled={busy} onClick={save}>{busy?'Opslaan…':'Locatie opslaan'}</button>}</div></section></div>}
