"use client";
import { FormEvent, useEffect, useState } from "react";
import { api, ApiError, formatDate } from "@/lib/api";
import { Icon } from "@/components/icons";

type Role={id:string;name:string};type User={id:string;email:string;username:string;displayName:string;active:boolean;lastLoginAt?:string;roles:Array<{role:Role}>};
export default function Users(){const[users,setUsers]=useState<User[]>([]);const[roles,setRoles]=useState<Role[]>([]);const[show,setShow]=useState(false);const[error,setError]=useState("");const[busy,setBusy]=useState(false);const[form,setForm]=useState({email:"",username:"",displayName:"",password:"",roleId:""});
  const load=async()=>{try{const[u,r]=await Promise.all([api<{users:User[]}>("/users"),api<{roles:Role[]}>("/roles")]);setUsers(u.users);setRoles(r.roles);if(!form.roleId&&r.roles[0])setForm(f=>({...f,roleId:r.roles[0]!.id}));}catch(e){setError(e instanceof ApiError?e.message:"Laden mislukt.")}};useEffect(()=>{load()},[]);
  const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{await api("/users",{method:"POST",body:JSON.stringify({...form,roleIds:[form.roleId]})});setShow(false);setForm({email:"",username:"",displayName:"",password:"",roleId:roles[0]?.id??""});await load();}catch(e){setError(e instanceof ApiError?e.message:"Gebruiker aanmaken mislukt.")}finally{setBusy(false)}};
  const toggle=async(u:User)=>{setBusy(true);setError("");try{await api(`/users/${u.id}`,{method:"PATCH",body:JSON.stringify({active:!u.active})});await load()}catch(e){setError(e instanceof ApiError?e.message:"Wijzigen mislukt.")}finally{setBusy(false)}};
  return <><div className="page-header"><div><h1>Gebruikers</h1><p>Beheer accounts, rollen en toegang tot het platform.</p></div><button className="button" onClick={()=>setShow(!show)}><Icon name="plus"/>Gebruiker toevoegen</button></div>{error&&<div className="alert error">{error}</div>}{show&&<form className="card" onSubmit={submit} style={{marginBottom:20}}><div className="card-header"><h2>Nieuwe gebruiker</h2></div><div className="form-grid"><div className="field"><label>Weergavenaam</label><input required value={form.displayName} onChange={e=>setForm({...form,displayName:e.target.value})}/></div><div className="field"><label>Gebruikersnaam</label><input required value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/></div><div className="field"><label>E-mailadres</label><input type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div><div className="field"><label>Rol</label><select value={form.roleId} onChange={e=>setForm({...form,roleId:e.target.value})}>{roles.map(r=><option value={r.id} key={r.id}>{r.name}</option>)}</select></div><div className="field full"><label>Tijdelijk wachtwoord</label><input type="password" minLength={12} required autoComplete="new-password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><small>Minimaal 12 tekens, hoofdletters, kleine letters en cijfers. Deel dit niet via onveilige kanalen.</small></div></div><div className="actions"><button type="button" className="button secondary" onClick={()=>setShow(false)}>Annuleren</button><button className="button" disabled={busy}>Gebruiker opslaan</button></div></form>}<section className="card"><div className="table-wrap"><table><thead><tr><th>Gebruiker</th><th>Gebruikersnaam</th><th>Rol</th><th>Laatste login</th><th>Status</th><th>Actie</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><strong>{u.displayName}</strong><br/><small>{u.email}</small></td><td>{u.username}</td><td>{u.roles.map(r=>r.role.name).join(", ")}</td><td>{formatDate(u.lastLoginAt)}</td><td><span className={`badge ${u.active?"green":"gray"}`}>{u.active?"Actief":"Uitgeschakeld"}</span></td><td><button className="button secondary" disabled={busy} onClick={()=>toggle(u)}>{u.active?"Uitschakelen":"Activeren"}</button></td></tr>)}</tbody></table></div></section></>}
