"use client";
import { FormEvent, useEffect, useState } from "react";
import { PERMISSIONS } from "@anpr/shared";
import { api, ApiError } from "@/lib/api";

type Group={id:string;name:string;description?:string|null;color:string;icon?:string|null;active:boolean;hitEnabled:boolean;reasonRequired:boolean;_count:{members:number}};
const empty={name:"",description:"",color:"#dc2626",icon:"",active:true,hitEnabled:true,reasonRequired:true};

export default function GroupsPage(){
  const[groups,setGroups]=useState<Group[]>([]);const[form,setForm]=useState(empty);const[editing,setEditing]=useState<string>();
  const[canManage,setCanManage]=useState(false);const[error,setError]=useState("");const[success,setSuccess]=useState("");const[busy,setBusy]=useState(false);
  const load=async()=>{const[g,me]=await Promise.all([api<{groups:Group[]}>("/plate-groups"),api<{user:{permissions:string[]}}>("/auth/me")]);setGroups(g.groups);setCanManage(me.user.permissions.includes(PERMISSIONS.PLATES_MANAGE));};
  useEffect(()=>{load().catch(e=>setError(e instanceof Error?e.message:"Groepen laden mislukt."))},[]);
  const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError("");setSuccess("");try{await api(editing?`/plate-groups/${editing}`:"/plate-groups",{method:editing?"PATCH":"POST",body:JSON.stringify({...form,icon:form.icon.trim()||null})});setSuccess(editing?"Groep gewijzigd en opgeslagen.":"Groep aangemaakt.");setEditing(undefined);setForm(empty);await load()}catch(e){setError(e instanceof ApiError?e.message:"Opslaan mislukt.")}finally{setBusy(false)}};
  const edit=(group:Group)=>{setEditing(group.id);setForm({name:group.name,description:group.description??"",color:group.color,icon:group.icon??"",active:group.active,hitEnabled:group.hitEnabled,reasonRequired:group.reasonRequired});setSuccess("");window.scrollTo({top:0,behavior:"smooth"})};
  const remove=async(group:Group)=>{if(!confirm(`Groep ${group.name} verwijderen?`))return;setBusy(true);setError("");try{const result=await api<{message?:string}>(`/plate-groups/${group.id}`,{method:"DELETE"});setSuccess(result?.message??"Groep verwijderd.");await load()}catch(e){setError(e instanceof ApiError?e.message:"Verwijderen mislukt.")}finally{setBusy(false)}};
  return <><div className="page-header"><div><h1>Groepen</h1><p>Beheer signalerings- en organisatielijsten.</p></div></div>{error&&<div className="alert error">{error}</div>}{success&&<div className="alert success">{success}</div>}{canManage&&<form className="card management-form" onSubmit={submit}><h2>{editing?"Groep bewerken":"Groep toevoegen"}</h2><div className="form-grid"><div className="field"><label>Naam *</label><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div className="field"><label>Kleur</label><input type="color" value={form.color} onChange={e=>setForm({...form,color:e.target.value})}/></div><div className="field full"><label>Omschrijving</label><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div><div className="field"><label>Icooncode (optioneel)</label><input value={form.icon} onChange={e=>setForm({...form,icon:e.target.value})} placeholder="alert"/></div><div className="checkbox-stack"><label className="checkbox"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/>Groep actief</label><label className="checkbox"><input type="checkbox" checked={form.hitEnabled} onChange={e=>setForm({...form,hitEnabled:e.target.checked})}/>Hitdetectie actief</label><label className="checkbox"><input type="checkbox" checked={form.reasonRequired} onChange={e=>setForm({...form,reasonRequired:e.target.checked})}/>Reden verplicht</label></div></div><div className="actions">{editing&&<button type="button" className="button secondary" onClick={()=>{setEditing(undefined);setForm(empty)}}>Annuleren</button>}<button className="button" disabled={busy}>{busy?"Opslaan…":"Opslaan"}</button></div></form>}<section className="card"><div className="table-wrap"><table><thead><tr><th>Groep</th><th>Kleur</th><th>Kentekens</th><th>Hitdetectie</th><th>Status</th>{canManage&&<th>Acties</th>}</tr></thead><tbody>{groups.map(group=><tr key={group.id}><td><strong>{group.name}</strong><small className="block-muted">{group.description}</small></td><td><span className="color-dot" style={{background:group.color}}/>{group.color}</td><td>{group._count.members}</td><td><span className={`badge ${group.hitEnabled?"red":"gray"}`}>{group.hitEnabled?"Aan":"Uit"}</span></td><td><span className={`badge ${group.active?"green":"gray"}`}>{group.active?"Actief":"Inactief"}</span></td>{canManage&&<td><div className="inline-actions"><button className="button secondary" onClick={()=>edit(group)}>Bewerken</button><button className="button danger" disabled={busy} onClick={()=>remove(group)}>Verwijderen</button></div></td>}</tr>)}{!groups.length&&<tr><td colSpan={canManage?6:5}>Nog geen groepen.</td></tr>}</tbody></table></div></section></>;
}
