"use client";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import { api, formatDate } from "@/lib/api";
import { directions, vehicleColors, vehicleTypes } from "@/lib/vehicle-labels";

export default function PlateDossier(){
  const{normalized}=useParams<{normalized:string}>();const[data,setData]=useState<any>();const[error,setError]=useState("");const[page,setPage]=useState(1);
  useEffect(()=>{setError("");api(`/plates/${encodeURIComponent(normalized)}?page=${page}&limit=25`,{cache:"no-store"}).then(setData).catch(e=>setError(e.message))},[normalized,page]);
  if(error)return <div className="alert error">{error}</div>;if(!data)return <div className="loading"><span className="spinner"/>Kentekendossier laden…</div>;
  const plate=data.plate;
  return <><div className="page-header"><div><h1>{plate.displayLicensePlate}</h1><p>Kentekendossier en losse waarnemingen.</p></div><Link href="/plates" className="button secondary">Terug</Link></div><div className="alert info"><strong>Let op:</strong> Dit zijn losse waarnemingen en geen gegarandeerde realtime locatiebepaling.</div><section className="card"><div className="detail-list"><div><span>Genormaliseerd</span><strong>{plate.normalizedLicensePlate}</strong></div><div><span>Waarnemingen</span><strong>{data.total}</strong></div><div><span>Eerste waarneming</span><strong>{formatDate(data.firstSeenAt)}</strong></div><div><span>Laatste waarneming</span><strong>{formatDate(data.lastSeenAt)}</strong></div><div><span>Reden</span><strong>{plate.reason??"—"}</strong></div><div><span>Status</span><strong>{plate.active===false?"Inactief":"Actief/alleen waargenomen"}</strong></div></div><p><strong>Groepen:</strong> {plate.groups.length?plate.groups.map((g:any)=>g.name).join(", "):"Geen"}</p>{plate.description&&<p><strong>Omschrijving:</strong> {plate.description}</p>}{plate.note&&<p><strong>Opmerking:</strong> {plate.note}</p>}<p><strong>Camera’s:</strong> {data.cameras.map((c:any)=>c.name).join(", ")||"Geen"}</p><p><strong>Kleuren:</strong> {data.colors.map((c:string)=>vehicleColors[c]??c).join(", ")||"Geen"}</p><p><strong>Voertuigtypen:</strong> {data.types.map((t:string)=>vehicleTypes[t]??t).join(", ")||"Geen"}</p></section><section className="card" style={{marginTop:18}}><h2>Historie</h2><div className="dossier-history">{data.observations.map((item:any)=><Link href={`/passages/${item.id}`} className="history-row" key={item.id}><div className="history-thumb">{item.vehicleImage1ObjectId?<img src={`/api/passages/${item.id}/image/overview`} alt="Voertuig"/>:item.plateImageObjectId?<img src={`/api/passages/${item.id}/image/plate`} alt="Kenteken"/>:<span>Geen foto</span>}</div><div><strong>{formatDate(item.timestamp,item.timeZone)}</strong><span>{item.camera.name} · {item.camera.location}</span><span>{vehicleColors[item.vehicleColor]??item.vehicleColor} · {vehicleTypes[item.vehicleType]??item.vehicleType} · {directions[item.direction]??item.direction}</span></div>{item.source==="DEMO"&&<span className="badge amber">DEMO</span>}</Link>)}{!data.observations.length&&<div className="empty">Nog geen waarnemingen.</div>}</div>{data.total>data.limit&&<div className="pagination"><button className="button secondary" disabled={page===1} onClick={()=>setPage(value=>value-1)}>Vorige</button><span>Pagina {page} van {Math.ceil(data.total/data.limit)}</span><button className="button secondary" disabled={page*data.limit>=data.total} onClick={()=>setPage(value=>value+1)}>Volgende</button></div>}</section></>;
}
